### ISSUE TITLE
Create a new CSW harvester

### ISSUE THREAD

**Issue by avdata99** [GSA/datagov-ckan-multi#103]
Part of EPIC at #91. Migrate the [geodatagov](https://github.com/GSA/ckanext-geodatagov/tree/master/ckanext/geodatagov) CKAN extension. 

**Create a new CSW harvester** based on the previous harvester: [GeoDataGovCSWHarvester](https://github.com/GSA/ckanext-geodatagov/blob/80b72945926134f0d9d3fb59741284332672cac4/ckanext/geodatagov/harvesters/arcgis.py#L61)

## Tasks

* [ ] Analyse existing harvester code. Check which fork of the spatial extension we are using. Maybe it's [GSA's](https://github.com/GSA/ckanext-spatial)?
* [ ] Write notes describin the process
* [ ] Write some tests
* [ ] Port code to new setup
* [ ] Find "real-life" files we can use for testing
* [ ] Test in live environment (?) -- this might come later

**Comment by avdata99** [comment]
Real Life cases (from catalog.data.gov):
 - Alaska LCC CSW Server: http://metadata.arcticlcc.org/csw
 - NC OneMap CSW: http://data.nconemap.com/geoportal/csw?Request=GetCapabilities&Service=CSW&Version=2.0.2
 - USACE Geospatial CSW: http://metadata.usace.army.mil/geoportal/csw?Request=GetCapabilities&Service=CSW&Version=2.0.2
 - 2017_arealm: https://meta.geo.census.gov/data/existing/decennial/GEO/GPMB/TIGERline/TIGER2017/arealm/
 - GeoNode State CSW: http://geonode.state.gov/catalogue/csw?service=CSW&version=2.0.2&request=GetRecords&typenames=csw:Record&elementsetname=brief
 - OpenTopography CSW: https://portal.opentopography.org/geoportal/csw

**Comment by tkprmr** [comment]
@jqnatividad to ask Adam to see if he can help @avdata99 on this

**Comment by avdata99** [comment]
Neither the GSA or CKAN versions of _ckanext-spatial_ refers to a _bureau_code_.
This field is one of many required for _USMetadata_ schema.

I needed to [set some default values](https://gitlab.com/datopian/ckan-ng-harvest/blob/89b55220b6fc29ac0560af1fb1a62885bce2a0ef/libs/harvester/adapters/datasets/csw.py#L64-74) for this fields since we are not able to create datasets at CKAN without them.

Other examples:

```
'bureauCode': '000:00',
'programCode': '000:000',
'dataDictionary': 'http://missing.data.dictionary.com',
'dataQuality': 'false',
'primaryITInvestmentUII': '000-000000000',
```
Maybe I'm missing something here.
How we harvest CSW today?
Are data.gov using USMetadata schema today with CKAN 2.3?

With these default values we are able to harvest CSW resources:
![image.png](https://images.zenhubusercontent.com/5d0fa29f8356d802835f2561/7ffbcd67-bd88-4ff5-96ca-fbd7c3e41683)

The [same resource at data.gov]( https://catalog.data.gov/dataset/syria-idpsites-2015jun11-hiu-usdos) is not using (for example) a _bureau code_.

**Comment by adborden** [comment]
@avdata99 the USMetadata extension is only used in Inventory. It is not used in [Catalog](https://github.com/GSA/datagov-deploy/blob/f65c64d3885458279b69741cd24b3340bf352753/ansible/roles/software/ckan/catalog/ckan-app/templates/etc/ckan/production.ini.j2#L127) where the harvesters run.

**Comment by tkprmr** [comment]
@adborden needs to test it once the sandbox is ready with this funcationality #137

**Comment by tkprmr** [comment]
@avdata99 need to get it ready for testing and notify him once ready for testing

**Comment by adborden** [comment]
Following instructions [here](https://gitlab.com/datopian/ckan-ng-harvest/blob/develop/docker.md) but wasn't sure what environment variables needed to be filled in. `docker-compose up` failed with

```
Creating ckan-ng-harvest_webserver_1 ... error

ERROR: for ckan-ng-harvest_webserver_1  Cannot create container for service webserver: invalid IP address in add-host: ""

ERROR: for webserver  Cannot create container for service webserver: invalid IP address in add-host: ""
ERROR: Encountered errors while bringing up the project.
```

**Comment by avdata99** [comment]
> Following instructions [here](https://gitlab.com/datopian/ckan-ng-harvest/blob/develop/docker.md) but wasn't sure what environment variables needed to be filled in. `docker-compose up` failed with
> 
> ```
> Creating ckan-ng-harvest_webserver_1 ... error
> 
> ERROR: for ckan-ng-harvest_webserver_1  Cannot create container for service webserver: invalid IP address in add-host: ""

I'm checking

**Comment by avdata99** [comment]
@adborden: At _services.webserver.environment_ you should define CKAN_API_KEY and CKAN_BASE_URL.  
This points to the CKAN instance you need to harvest to.  

At [CKAN Cloud Docker](https://github.com/avdata99/ckan-cloud-docker/blob/7aac946ee7a732379a9c6b7a933ebf5f90b358c7/.docker-compose-harvester_ng.yaml#L41) we use `CKAN_API_KEY=READ_FROM_DB` to read credentials directly from database. Here we need to difine this.  

I added this noted to _docker.md_

**Comment by adborden** [comment]
If we're using Docker Compose, should we just include a CKAN instance as part of the setup?

**Comment by avdata99** [comment]
> If we're using Docker Compose, should we just include a CKAN instance as part of the setup?

The harvester could run with every CKAN instance, local or remote. The Harvester integrated with CKAN works [at Ckan Cloud Docker](https://github.com/avdata99/ckan-cloud-docker/blob/master/start-harvester.md) and we have a [pending PR](https://github.com/ViderumGlobal/ckan-cloud-docker/pull/68) tu run it. In our demos we used this environment.

**Comment by adborden** [comment]
Right, it's a good idea to design it that way. But for developer usability, doesn't it make sense to build it so that there is no external dependency on CKAN? Just like how there is no external dependency on Apache Airflow.

**Comment by adborden** [comment]
*or the external dependency on CKAN is optional.

**Comment by kimwdavidson** [comment]
We'll deploy this and demo the JSON harvester before discussing this ticket.

**Comment by avdata99** [comment]
> Right, it's a good idea to design it that way. But for developer usability, doesn't it make sense to build it so that there is no external dependency on CKAN? Just like how there is no external dependency on Apache Airflow.

We added [a yaml override file](https://gitlab.com/datopian/ckan-ng-harvest/blob/develop/docker-compose-override.sample.yml) in order to add another CKAN instance (with some notes at [docker.md](https://gitlab.com/datopian/ckan-ng-harvest/blob/develop/docker.md)). I add @akariv here to discuss the best way to improve this.
