### ISSUE TITLE
Create a new GeoPortal harvester

### ISSUE THREAD

**Issue by avdata99** [GSA/datagov-ckan-multi#107]
Part of EPIC at #91. Migrate the [geodatagov](https://github.com/GSA/ckanext-geodatagov/tree/master/ckanext/geodatagov) CKAN extension. 

**Create a new GeoPortal harvester** based on the previous harvester: [GeoDataGovGeoportalHarvester](https://github.com/GSA/ckanext-geodatagov/blob/80b72945926134f0d9d3fb59741284332672cac4/ckanext/geodatagov/harvesters/arcgis.py)

## Tasks

* [ ] Analyse existing harvester code.
* [ ] Write notes describin the process
* [ ] Write some tests
* [ ] Port code to new setup
* [ ] Find "real-life" files we can use for testing
* [ ] Test in live environment (?) -- this might come later
