### ISSUE TITLE
More work on Jenkins / Airflow setup for harvesting

### ISSUE THREAD

**Issue by avdata99** [GSA/datagov-ckan-multi#114]
To polish up an admin and/or CLI interface for running harvester and providing overview.

First Airflow script working: https://gitlab.com/datopian/ckan-ng-harvest/blob/develop/automate-tasks/airflow/harvest_with_airflow.py   

refer to zenhub issue # 137 which is related issue to this one

## Acceptance Criteria

* [x] Way to run / rerun harvesters
* [x] See status of running or run harvester

## Tasks

* [x] Investigate jenkins as runner for airflow (is it needed)
* [x] Polish up airflow runner
* [ ] ~~Automate deployment (configuration as code)~~ now in #129

**Comment by jqnatividad** [comment]
In preparation for testing and installation from scratch (https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/121), an INSTALL.md was created by @avdata99

**Comment by jqnatividad** [comment]
On a related note, it'd be great if we can provision external access to a devt and UAT environment.  Opened ticket here - https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/133

**Comment by jqnatividad** [comment]
As discussed during Aug 29 check-in, there is already an AWS sandbox environment that the team can use per @adborden.

We will use the Sandbox environment to test the new Harvesters.  Created #137 to track this so we can close this issue.

**Comment by avdata99** [comment]
Locally Airflow is working and seems a good plan for this.
We will continue on #137 and open new tickets if any problem presents
