### ISSUE TITLE
Upgrade from V2.3 to V2.8

### ISSUE THREAD

**Issue by tkprmr** [GSA/datagov-ckan-multi#125]
This follows up the analysis work in #83 (and in #95 re collections).

Plan as discussed with @adborden is:

* A cut-over to a clean system on v2.8 and reimplement what we need 
* Most important is harvesting => want to see that first … [we are working on that now]
  * data.json
  * then geo harvesters
  * Features like: Retry failed jobs … and more insight into the process. How many jobs are queued up. How many are backed up … 

Then ...

* Theme
* Collections: room to improve/reinvent that feature (data.json harvester ties in …) -- further discussion on this
* Legacy formats: a lot of old datasets with old metadata
  * E.g. have a lot of ISO 19139 … and could convert that into something newer …  Whilst retaining the original source … (“show your work”)

Spike solution approach in general.

## Acceptance Criteria

* [ ] We have a running version of data.gov catalog with all datasets running on ckan v2.8
  * [ ] Theme applied
  * [ ] Harvesting is running
* [ ] This is running in the new multi-tenant / ckan cloud environment

## Tasks

* [ ] 2.8 clean install
* [ ] Apply / upgrade theme - #130 
* [ ] Integrate harvesting
* [ ] Check what is missing (e.g. are collections important)?
* [ ] Migrate data
* [ ] ...

## Old from Tejas

This is an EPIC to cover following items from the Roadmap

- 2.8 clean install with core functionality (harvest, theme, collections)
- Datastore preview improvement planning
- Legacy metadata format compatibility
- Migrate theme to 2.8
- Test moving existing catalog to new platform, document performance per type of source

**Comment by tkprmr** [comment]
Assigning to @jqnatividad to clean up the story links associated with this ticket as per discussion in check-in call today

**Comment by rufuspollock** [comment]
@kimwdavidson the retitle of this issue is incorrect - the migration of theme is #130. This is the epic issue for the complete Upgrade from V2.3 to V2.8

**Comment by kimwdavidson** [comment]
Out of date, replaced with #213
