### ISSUE TITLE
Logging Setup is Automated in Code / Config + Docs

### ISSUE THREAD

**Issue by rufuspollock** [GSA/datagov-ckan-multi#127]
This is a follow on from #59 where we had an ELK set up in Jenkins.

As an operator, I want the logging stack defined in code and deployed automatically with the existing stack so that I can make changes to infrastructure via auditable, versioned code changes and deploy those changes the same way I deploy the rest of the stack.

## Acceptance Criteria

* [ ] You can now deploy the logging as part of overall deployment
* [ ] You can read how to do this in the docs

## Tasks

* [x] Helm chart or similar for the setup
* [ ] Documentation of the set up in the CCO docs
* [ ] set up domain and authentication on kibana instance

**Comment by tkprmr** [comment]
related to #135

**Comment by tkprmr** [comment]
@adborden to clarify this ticket with proper wording / details

**Comment by adborden** [comment]
@jqnatividad clarified the user story, does that make more sense?

**Comment by akariv** [comment]
Adding a technical checklist for @aluminiumgeek :

- [ ] Create a helm chart for the ELK setup in `ckan-cloud-helm` (similar to the provisioning one https://github.com/ViderumGlobal/ckan-cloud-helm/tree/master/provisioning)
- [ ] Release a new version of `ckan-cloud-helm` so that the new chart is in the repository
- [ ] Add a new app type to `ckan-cloud-operator` (similar to the provisioning one https://github.com/datopian/ckan-cloud-operator/blob/master/ckan_cloud_operator/providers/apps/deployment/helm/type_provisioning.py)
- [ ] Make sure that only kibana is exposed externally to the cluster (and make sure proper authentication is set up for it)
- [ ] Make sure that the hostname of the logstash service is always stored in a centralized secret in the `ckan-infra` namespace (so that it can be picked up by the ckan instances)

**Comment by aluminiumgeek** [comment]
Released a new version (v0.0.9) of `ckan-cloud-helm`, and added a new type to `ckan-cloud-operator`.

Kibana allows only authentication with X-pack extension. So I'm currently working on adding this to the helm repo and make auth credentials configurable.

**Comment by aluminiumgeek** [comment]
I also need to create a entry for Traefik with SSL certificate to be able to run Kibana on subdomain.

**Comment by akariv** [comment]
Thanks - cco handles the routing and ssl certificates for you as far as I
remember.

Can you put here the links to the relevant prs so I can review them?

**Comment by akariv** [comment]
@aluminiumgeek ^

**Comment by aluminiumgeek** [comment]
@akariv the work is currently pushed to `master` in `ckan-cloud-operator` and `ckan-cloud-helm` repos.

**Comment by aluminiumgeek** [comment]
I was unable to set up Kibana auth with X-pAck extension. I'm going to use BasicAuth with Traefik.

**Comment by adborden** [comment]
On Thu, 2019-09-26 at 04:39 -0700, Mikhail Mezyakov <notifications@github.com> wrote:
> I was unable to set up Kibana auth with X-pAck extension. I'm going to use BasicAuth with Traefik.

Thanks Mikhail, can you document some of the issues you ran into setting
up X-pack? BasicAuth will be okay for now, but at some point we'll need
to setup authentication through SAML2 (via login.gov). It would be good
to at least document some of the challenges we're going to face when
we're ready to take on that work.


--
Aaron D Borden
Human and hacker

**Comment by aluminiumgeek** [comment]
Purged manually installed ELK stack from the cluster, and reinstalled it with CCO:

```
$ ckan-cloud-operator apps deployment helm create --chart-repo ckan-cloud --chart-release-name elk --wait-ready --app-type elk --instance-id elk --instance-name elk
$ ckan-cloud-operator apps update elk
```

I also had to manually update DNS record for Kibana (`aws_manager.update_dns_record('ckan-cloud-app-elk', 'datagov.us',  '<LB hostname>')`) with CCO, because the default one didn't point to the Kibana instance

**Comment by akariv** [comment]
Mikhail, please integrate with the routes mechanism in CCO so that DNS and
HTTPS are set-up correctly and automatically.

**Comment by jqnatividad** [comment]
@adborden on X-Pack, the main challenge is that even though its open source, it requires a subscription.  That's why @aluminiumgeek is just doing Basic Auth with Traefik.

See https://www.elastic.co/what-is/open-x-pack

**Comment by mogul** [comment]
Note that most of the functionality in x-pack is now available via libre+gratis open community add-ons, maintained as a distribution that track Elastic's upstream releases: https://opendistro.github.io/for-elasticsearch/

**Comment by mogul** [comment]
Note you can also install the add-ons one-by-one, so you can just grab the Security plugin without bringing in the others: 
https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/

**Comment by aluminiumgeek** [comment]
@mogul thank you. I dIdn't know about opendistro addons. I'm checking this out.

**Comment by akariv** [comment]
https://ckan-cloud-app-elk.datagov.us is deployed using CCO.

Just missing basic auth on kibana.

**Comment by tkprmr** [comment]
@adborden to help with QA and add comments

**Comment by adborden** [comment]
Thanks, looks good.
