### ISSUE TITLE
Harvesting Deployment into CKAN Cloud

### ISSUE THREAD

**Issue by rufuspollock** [GSA/datagov-ckan-multi#129]
We want to deploy the harvesting as part of the multi-tenant / CKAN Cloud.

## Acceptance criteria

* [ ] Harvesting system deployed as part of CKAN Cloud deploy with config in code (helm etc)
* [ ] Admin interface is available

## Tasks

* [ ] Helm chart for this setup
  * [ ] Airflow
  * [ ] Runners for harvesting
* [ ] Tests
* [ ] Documentation

**Comment by kimwdavidson** [comment]
Duplicate of UAT provisioning ticket
