### ISSUE TITLE
v2.8 running with data.gov theme

### ISSUE THREAD

**Issue by rufuspollock** [GSA/datagov-ckan-multi#130]
We want to start migration of existing data.gov by booting CKAN v2.8 and migrating the theme.

## Acceptance Criteria

* [ ] Site running with theme

## Tasks

* [ ] Clean CKAN v2.8 install
* [ ] Migrate data.gov theme
* [ ] Use Bootstrap 3 to be compatible with CKAN 2.9
* [ ] Add tests

**Comment by avdata99** [comment]
We are working in a clean CKAN 2.8 instance at docker for local harvestings tests: https://gitlab.com/avdata99/docker-ckan-harvesting/.  

We already put some extension and plan to use it to test the theme migrated. We validate this idea with @jqnatividad

**Comment by thejuliekramer** [comment]
@adborden currently running into this issue https://github.com/GSA/catalog-app/issues/76, I will ping you on how to resolve

**Comment by thejuliekramer** [comment]
I was able to get this running in my local environment, what environment should this be running in to meet the acceptance criteria

**Comment by thejuliekramer** [comment]
Just noting that this config is needed when setting up in any new environment https://github.com/GSA/datagov-deploy/blob/develop/ansible/roles/software/ckan/catalog/ckan-app/templates/etc/ckan/production.ini.j2#L221

**Comment by jqnatividad** [comment]
@thejuliekramer please coordinate with @avdata99 to see if you can include the theme in the Docker image he's building.

**Comment by thejuliekramer** [comment]
Thanks @jqnatividad . Also going to request a login for data.gov from @adborden to see what the theming looks like from the logged in perspective.

**Comment by thejuliekramer** [comment]
Working on getting the theme running using this docker repo locally, https://github.com/ViderumGlobal/ckan-cloud-docker. I am having an issue with the install and pinged @akariv on GSA Slack for help. Is this the best way to reach him @jqnatividad?

**Comment by akariv** [comment]
Indeed it is :)

**Comment by thejuliekramer** [comment]
I was able to get the ckan cloud docker running but not the theme after trying for a couple hours - sent a message to @akariv on Slack and waiting for a response

**Comment by jqnatividad** [comment]
Also connected @thejuliekramer with Adrià to help with migrating the theme.

**Comment by thejuliekramer** [comment]
@jqnatividad I didn't realize you connected  me with Adria? Where can I reach them?

**Comment by thejuliekramer** [comment]
Spoke with Joel last week and he said we should move to Bootstrap 3 instead of 2. I started over on the theme this week with that in mind. Still working on the theming - this is more work than just small fixes now. Each page needs to be looked at. I had to set up the data.gov CKAN environment locally in order to work with the html and css files which took some time. I would say this is about 10% done.

**Comment by thejuliekramer** [comment]
Continuing work on this moving from bootstrap 2 to 3. Going to speak with @woodt soon on how we can integrate testing into the pipeline

**Comment by adborden** [comment]
Thanks all! If you end up on pulling in other folks over email, please CC
datagovhelp@

**Comment by thejuliekramer** [comment]
@jqnatividad I would like to connect with him either way, I can show him what I have been doing so far to get a code review of sorts

**Comment by thejuliekramer** [comment]
Connected with Tanvir about using the USDWS theme. It doesn't seem like the right move at this time because the work for moving to bootstrap 3 is done.

**Comment by thejuliekramer** [comment]
Continuing to work on testing tests and code changes in CKAN installed from source environment. Code is ready for QA - still working on getting tests running as part of the ckanext test suite

**Comment by thejuliekramer** [comment]
Able to now test that  the extension is able to be loaded but having trouble verifying that the stylesheet is loaded because the helper methods defined in the test are not working within the test. I opened an [issue](https://github.com/ckan/ckan/issues/5087) with CKAN and pinged the CKAN gitter channel for help. If we want to go ahead and move along from this task we can at minimum test that the extension is able to be loaded

**Comment by thejuliekramer** [comment]
Code is here: https://github.com/thejuliekramer/ckanext-datagovtheme Issue moved to https://github.com/GSA/datagov-ckan-multi/issues/204
