### ISSUE TITLE
EPIC: Automate provisioning of CCO managed clusters 

### ISSUE THREAD

**Issue by jqnatividad** [GSA/datagov-ckan-multi#184]
## User Story
As a GSA operator, I need to CCO installed via an automated CI/CD pipeline so that I can build in compliance and security checks within the pipeline to ensure CCO is meeting all controls.

## Details / tasks
- [ ] Automate the supporting infra setup (and ideally with a well used tool like terraform)
- [ ] Ensure docs are good and describe the canonical helm-based deploy method
- [ ] Create a first class option for not using minio and using cloud storage (s3, google cloud objects thing, azure objects thing)
- [ ] Create a streamlined flow for local development (e.g. to test new helm charts)
- [ ] Improve the CLI to allow creating the values file for helm based installations
- [ ] Merge the specific ckan and the generic paths for helm based installations
- [ ] Ensure good test coverage

## Acceptance Criteria
- [ ] CCO is deployed via GSA's automated CI/CD pipeline
- [ ] New CCO clusters can be deployed from scratch by a trained devop by just referring to the new documentation, in a manner consistent with TTS security and devops practices

**Comment by tkprmr** [comment]
@akariv to create additional tickets and link with this EPIC by 11/5 ( tuesday ) and start work on those tickets in current sprint 12

**Comment by jqnatividad** [comment]
@akariv updated the details/task list to reflect refactoring goals.

A follow-up meeting involving @adborden, @mogul and @woodt will be scheduled week of Nov 11 to start capturing GSA TTS requirements which will inform specs/implementation tickets for this epic.

**Comment by kimwdavidson** [comment]
Esteban to add new tickets to this epic

**Comment by kimwdavidson** [comment]
Duplicate. Closing
