### ISSUE TITLE
Create checklist to apply to repos that cover security compliance

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#190]
## User Story
As a team member, I want a checklist that I can follow when adding a source code repository to the CKAN Cloud system boundary so that I know exactly what measures need to be implemented for the repository to be covered by our compliance plan.

## Details / tasks
@woodt has a list of issues that cover specific measures that should be enabled on a repository. We want to collect that list into a single repository checklist in CONTRIBUTING.md.

## Acceptance Criteria
- [ ] Checklist lives in CONTRIBUTING, or similar document describing our team process
- [ ] Checklist includes common tooling we've used so far covering:
  - static and dynamic code analysis
  - dependency analysis
  - CI/CD
  - GH branch protection
- [ ] Some distinction is made between repo's that GSA owns vs upstream repos we consume

**Comment by woodt** [comment]
@aaron: so me thinks this checklist should be added to GSA/datagov-ckan-multi/CONTRIBUTING.md first, but then also to:

- GSA/ckanext-geodatagov
- GSA/ckanext-datagovtheme

and I suppose, pending fork resolution? :-)

- GSA/ckanext-datajson

some of the latter CONTRIBUTING docs haven't been updated in a while.

I'd also like to see equivalent text added to some of the Datopian repos (especially the NG harvester.)

So, a scope question: how far down the road of updating CONTRIBUTING docs shall I go?

**Comment by kimwdavidson** [comment]
Keep in ckan-multi, link to there from other repos
