### ISSUE TITLE
Authorize and book travel for GSA team to attend UX kickoff

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#191]
## Details
UX sessions booked for Dec 16-17, GSA team meeting Dec 18.

https://handbook.18f.gov/travel-guide-table-of-contents/

## Tasks
- [x] @mogul has a travel card and pre-travel work complete
- [x] Authorize travel from @philipashlock over email
- [x] @adborden books travel
- [x] @mogul books travel

**Comment by adborden** [comment]
All set.
