### ISSUE TITLE
Discovery: Manual and Auto Scaling

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#22]
As a platform admin, I can manually scale instances and instance processes, so that the platform can support the instances as needed

Look into scaling (how it could be done and done automatically)

## Acceptance criteria

Have a document detailing

* [x] the process for setting up auto scaling on a Kubernetes cluster on AWS/GCP
* [x] the process of adding or removing nodes from a Kubernetes cluster on AWS/GCP
* [x] the consideration for scaling up or down the cluster, i.e. how we measure capacity, being over capacity etc.

## Tasks

* [ ] Read the AWS and GCP docs
* [ ] Implement manual autoscaling in CCO (via CLI)
  * Add tests
* [ ] Test autoscaling itself with a dummy cluster
* [ ] (Optional) Set up automatic scaling - need to consult with John Jediny from data.gov to hear his preference on this

**Comment by rufuspollock** [comment]
Google Kubernetes engine has built-in scaler. AWS didn't, but there's stable/cluster-autoscaler helm package.
 
We updated CCO code adding CLI command that configures autoscaler for both cases (it installs the helm package if cluster is in AWS).
 
Cluster Autoscaler is a tool that automatically adjusts the size of the Kubernetes cluster when one of the following conditions is true:

- there are pods that failed to run in the cluster due to insufficient resources,
- there are nodes in the cluster that have been underutilized for an extended period of time and their pods can be placed on other existing nodes.

**Comment by rufuspollock** [comment]
FIXED.

@aluminiumgeek can you link docs / code on this that would fulfil acceptance criteria ... (if there are docs)

**Comment by aluminiumgeek** [comment]
[Autoscaling on GCP](https://github.com/ViderumGlobal/ckan-cloud-operator/blob/master/docs/PRODUCTION-GCLOUD-CLUSTER.md#optional-enable-autoscaling
)  
[Autoscaling on AWS](https://github.com/ViderumGlobal/ckan-cloud-operator/blob/master/docs/PRODUCTION-AWS-CLUSTER.md#optional-enable-autoscaling)
