### ISSUE TITLE
Data ingestion tool prototype

### ISSUE THREAD

**Issue by estebanruseler** [GSA/datagov-ckan-multi#260]
## Description

Prepare a clickable prototype to in able to fulfill OMB's milestone and to have pre-work done ahead of user-testing. The idea is that once the 1st round of user testing is complete we can update the prototype and iterate based on user feedback. 

Links: 
- [MyBalsamiq low-fidelity "prototype" ](https://balsamiq.cloud/s274fxc/pcybj9h/r2278)

## Acceptance Criteria
- [ ] We have a clickable prototype that fulfills OMB's milestone requirements
- [ ] We have a clickable prototype that is ready to be iterated upon based on user feedback

## Task list lo-fi prototype
 - [x] Alignment meeting between Hyon, Jacqueline, Kim, Tanvir, Esteban
 - [x] Feedback from Hyon, Jacqulien, Kim
 - [x] Tanvir incorporates feedback in 

## Task list hi-fi prototype
 - [x] Decide what to do this in html/css / InVision on top of xd (decided InVision/Xd due to rich commenting features)
 - [x] Tanvir to do first hi-fi prototype
 - [ ] Esteban review
 - [ ] WIP design files moved to CA folder
 - [ ] Incorporate any feedback
 - [ ] Share with team 
 - [ ] Incorporate any feedback to produce v0.2
 - [ ] iterate
 - [ ] final design files moved to CA folder
