### ISSUE TITLE
Implement collections integration for CKAN search

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#263]
## User Story

As a data.gov developer I want to isolate the collections feature related to CKAN search so that we can upgrade to CKAN 2.8.

**Acceptance Criteria**
* [ ] WHEN I search for a parent dataset (https://catalog.data.gov/dataset/general-schedule-and-locality-pay)
  THEN I see it in search results

* [ ] When I search for a child dataset (https://catalog.data.gov/dataset/general-schedule-and-locality-pay-1991)
  THEN I do not see the child dataset in the search results, but I do see the parent dataset in the results (https://catalog.data.gov/dataset/general-schedule-and-locality-pay)

* [ ] WHEN I click on a collection 
  THEN I can see all datasets that belong to that collection 
  AND I can search within a collection for datasets that belong to that collection 

## Create tickets for below:

**Task-list local dev** 
* [x] Investigate the if/how the other harvesters use `isPartOf` (ie check which metadata fields are saved by the harvester in order to determine parent/child relationship for collections - collection_package_id & collection_metatdata)
  * [x] Geo-dataportal (do this one first)
  * [x] WAF
  * [x] WAF-collections
  * [x] CSW
  * [x] pyZ3950
  * [x] Arcgis
  * [x] Doc
* [x] Double check there is no dependency for the Harvester ext:
   * [x] Yes, we have dependencies. The Data.json adds [datajson_collection](https://github.com/GSA/ckanext-datajson/blob/f4ac11c2d2041e64f8ec3976bd2df73511abda68/ckanext/datajson/harvester_base.py#L213) to source config to be used at the harvester ext to divide the harvest process [first for parents and then for children](https://github.com/GSA/ckanext-harvest/blob/bb4219462483029fd0b0d7a06403029987f38e89/ckanext/harvest/logic/action/update.py#L531). We already have the [Catalog-next#40](https://github.com/GSA/catalog.data.gov/issues/41) issue covering this.
* [x] Incorporate the "[fq commit](https://github.com/GSA/ckan/commit/3ef9f1be9667476d14ce4411d0e36bbdf81e00dc)" that filters our child datasets from site-wide searches
* [ ] Create unit tests 
* [ ] Create integration tests
* [ ] Mini-PR to Aaron (if he wants to review tests in this TDD approach)
* [x] Create the Collections code as per the analysis
  * [x] Check that our assumption is validated -- that the data.json, theme, and geodatagov extensions are not affected (this may be picked up by tests, but this is crucial so putting as a separate task item)
* [x] Look into [the n+1 bug](#Bonus---fixing-bugs-associated-with-current-implementation). Timebox this at 2 hours. If longer then create a separate issue for this. 
* [ ] Unit tests are green
* [ ] Integration tests are green

**Task-list sandbox** 
* [ ] Write integration tests if additional ones are required (?)
* [ ] Deploy to sandbox
* [ ] Integration and unit tests are green
* [ ] Seed some data or harvest (mock) data
* [ ] UAT for collection features is green

Once we have a functioning Catalog app running on CKAN 2.8 with the following extensions we can do final UAT testing
  * data.json, which needs the harvester ext
  * data.gov theme
  * geodatagov, which needs the spatial ext

**Comment by avdata99** [comment]
Starting TDD
 - PR for tests: https://github.com/GSA/ckanext-datagovcatalog/pull/5/files
 - PR for geoDataGov extension: https://github.com/GSA/ckanext-geodatagov/pull/130/files

**Comment by avdata99** [comment]
isPartOf is only used for DCAT-US sources. We manage the collection relationship in different ways for each source type.

[x] = upstreamed

| DataType | Collection notes | Harvester | Extension |
| --- | --------------------- | --------- | --------- |
|Datajson|Used at import stage [here](https://github.com/GSA/ckanext-datajson/blob/f4ac11c2d2041e64f8ec3976bd2df73511abda68/ckanext/datajson/harvester_base.py#L685-L689)|`DataJsonHarvester` inherits from `DatasetHarvesterBase` | datajson |
| Geo-dataportal| A Harvester for CSW servers, with customizations for data.gov) |Inherit from `CSWHarvester` and `GeoDataGovHarvester` | geodatagov |
| WAF [x] | We use `collection_package_id` at fork and upstream. Waf harvester [here](https://github.com/GSA/ckanext-spatial/blob/d9e8212e784e4235feb8d82355c3884feb2bf038/ckanext/spatial/harvesters/waf.py#L128). It's also [used at upstream](https://github.com/ckan/ckanext-spatial/blob/d1594b37902dd4ecefcb8fe872dfae7e0027541e/ckanext/spatial/harvesters/waf.py#L49) | `WAFHarvester` inherits from `SpatialHarvester`|spatial
| WAF-collections | We use `collection_package_id` at  `WAFCollectionHarvester.get_package_dict`, [here](https://github.com/GSA/ckanext-geodatagov/blob/4b13e7a6afee987055858b4773fc5ccaaf117ee9/ckanext/geodatagov/harvesters/waf_collection.py#L37-L43)  | `WAFCollectionHarvester` inherit from `GeoDataGovWAFHarvester` which inherit from `WAFHarvester` and `GeoDataGovHarvester` | spatial |
| CSW [x] | `CSWHarvester`: At the fork, we have a command in which we add the `collecion_package_id` extra. This command exists at upstream but didn't add the extra. At load pycsw [here](https://github.com/GSA/ckanext-spatial/blob/bd95c46dd2432aa4e269be520fdfab095554b3b7/bin/ckan_pycsw.py#L126). It's an internal command. **It doesn't exists upstream (for CSW)** | `GeoDataGovCSWHarvester` inherit from `CSWHarvester` and `GeoDataGovHarvester` | spatial
| Z3950 | It's covered by parent classes  | `Z3950Harvester` inherit from `GeoDataGovHarvester` -> `SpatialHarvester` | geodatagov |
| ArcGIS | It's covered by parent classes | `ArcGISHarvester` inherit from `SpatialHarvester` | geodatagov |
| Doc | It's covered by parent classes | `GeoDataGovDocHarvester` inherit from `DocHarvester` and `GeoDataGovHarvester` | geodatagov |

Aaron's Harvest Source Report 

| source_type |	total_datasets | count |
| ----------- | -------------- | ----- |
| waf-collection	|781731	|379
| datajson	|72583	|150
| waf	|32333	|466
| ckan | 26021	|2
| csw | 398	| 7
| z3950 | 177 | 3 | 
| single-doc | 3 | 16
| geoportal | 0	| 5
| arcgis | 0| 5
| **Grand Total** | **913246** | **1033** |

**Comment by thejuliekramer** [comment]
Created separate issue for dataset count N+1 bug https://github.com/GSA/datagov-ckan-multi/issues/337

**Comment by kimwdavidson** [comment]
Duplicate. closing
