### ISSUE TITLE
Improve Catalog app

### ISSUE THREAD

**Issue by avdata99** [GSA/datagov-ckan-multi#264]
## Description. 

This is a follow on to #259 ([zenhub link](https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/259). In 259 we wanted a catalog app based on CKAN 2.8 working with OKF Docker image. This issue is to improve the catalog app. 

**[Link to WIP analysis doc](https://hackmd.io/obF4RqFqQy2914eBrQQ44Q?both)** 

## User Story

As a GSA developer, I want a clean CKAN 2.8 catalog-app so that I'm able to start moving forks to upstream versions.

## Acceptance Criteria
- [ ] We don't have unused code in the Catalog-app.
- [ ] We have a clean requirements file ready to start adding extensions
   - [ ] Dev**SEC**Ops is green
- [ ] Tests are green

## Task list
- [ ] Remove redundant code
   - [ ] Identify unused and redundant code
   - [ ] Create a mini plan of work to remove it
   - [ ] Aaron review to check we're on the right path
   - [ ] Remove unused and redundant code
- [ ] Identify what improvements to be made to the way we import libraries 
- [ ] Check, clean and  update the requirements file just with CKAN 2.8 requirements and share with team so we start using this
   - [ ] Involve Tom in running the security tests on libs

## Details / tasks

By moving from CKAN 2.3 GSA fork to OKF CKAN 2.8 we need to deprecate old code and define new version for pip packages.

**Comment by kimwdavidson** [comment]
closing and will create a new ticket for defined work
