### ISSUE TITLE
Evaluate and implement test strategy for updated forks of pysaml2 and ckanext-saml

### ISSUE THREAD

**Issue by starsinmypockets** [GSA/datagov-ckan-multi#265]
# User Story

As a data.gov maintainer I want to ensure that all code is covered by tests so that I can remain confident that the system is performing as expected.

# Tasks

- [ ] Documented General Analysis of testing approach for updated libraries
- [ ] If possible implement automated testing strategy
- [ ] Identify and document gaps in coverage

# Acceptance

- [ ] https://github.com/GSA/ckanext-saml2/tree/datagov/v0.4.0 branch has passing tests or equivalent (eg expected tests pass) + coverage is noted
- [ ] https://github.com/GSA/pysaml2/tree/datagov/v4.9.0 branch has passing tests or equivalent (eg expected tests pass) + coverage is noted
- [ ] testing tickets created for additional gsa-supported forks

# Analysis

TODO - document analysis here
