### ISSUE TITLE
Remove Code Related to Tracking Updates

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/datagov-ckan-multi#271]
## User Story

As a developer, I want to determine if these code changes [1](https://github.com/ckan/ckan/commit/add3a04920d79a038d3036eabbf13b1155e05047) & [2](https://github.com/ckan/ckan/commit/fefc27367557df4b0eb6944733b07c9b6a284933) related to tracking updates have been moved into upstream CKAN so that we can use the [OKF version of CKAN](https://github.com/ckan/ckan) instead of GSA's fork. 

## Acceptance Criteria
- [ ] Code is no longer in fork, and fork still works
- [ ] Code is determined to be upstream
- [ ] If code is determined necessary, moved to an extension

## Details / tasks
- [ ] determine if code is upstream
- [ ] if not upstream, determine if code needs to be moved to an extension or only removed
- [ ] remove custom code [1](https://github.com/ckan/ckan/commit/add3a04920d79a038d3036eabbf13b1155e05047) & [2](https://github.com/ckan/ckan/commit/fefc27367557df4b0eb6944733b07c9b6a284933) from GSA CKAN datagov branch
