### ISSUE TITLE
 Deterministic builds for catalog app

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#283]
## User Story

As a data.gov developer, I want the build artifact of the new catalog app to be deterministic with pinned versions of dependencies so that the code I write works the same in my colleagues' environments as well as sandbox, staging, and production

## Acceptance criteria

- [x] WHEN I have my local development environment in a state I want to deploy
      THEN I can run a command to generate a list of pinned dependencies
- [x] WHEN I push my development code to master
      THEN the generated list of pinned dependencies (*) can be installed in a production-like deploy target

## Tasks
- [x] Determine package management solution (as-is pip, pip-compile, pipenv)
- [x] Implement package management solution
- [x] Ensure that development env builds local docker using frozen requirements, or can be configured to do so (ie `make dev --frozen`)
- [x] Test locally (manually)
- [ ] Test locally (automated -- not sure how practical this is)
- [x] Test in sandbox (aka ansible) env

**Comment by woodt** [comment]
As a mini-spike, I'm going to start with the base requirements for CKAN 2.8.4 and generate frozen requirements using raw pip, pip-compile, pipenv, and poetry and compare.

**Comment by woodt** [comment]
Pushed my mini-spike work to https://github.com/GSA/catalog.data.gov/tree/feature/requirements-spike.

**Comment by woodt** [comment]
Collecting some notes about the issues: https://hackmd.io/Zz_lCjwoTM-rTdYgtFgFcA?view

**Comment by woodt** [comment]
# Python package installation in the OKFN "docker-ckan" containers

## ckan-base Docker image

At _image build_ time, the *ckan-base* Docker image:

* Runs a `pip install` in source mode of the CKAN GitHub repository.  The URL and branch are set by environment variables `GIT_URL` and `GIT_BRANCH` which default to `https://github.com/ckan/ckan.git` and `ckan-2.8.4` respectively.
* Runs a `pip install` of the `requirements.txt` file found in the CKAN git repository.
* Runs a `pip install` in source mode of the `ckanext-envvars` GitHub repo (untagged.)

## ckan Docker image (derived from ckan-base)

By default, at _image build_ time this image does not add any packages.  However, the comments in the Dockerfile suggest that you should add `RUN pip install ...` directives for any CKAN extensions needed by your instance.

## ckan-dev Docker image (derived from ckan-base)

At _image build_ time, this image adds the CKAN development dependencies by running `pip install` against the `dev-requirements.txt` file found in the CKAN GitHub repository.  Note that (for some reason) the GitHub URL is hard-wired, although the branch can be configured via `GIT_BRANCH` as in the *ckan-base* Docker image.  So, potentially the *ckan-base* image could use one GitHub repo as the source for CKAN, and *ckan-dev* image could use a different repo.

## Runtime package installation

At runtime, the *ckan-dev* image will attempt to install requirements for CKAN extensions it finds in the `src_extensions` directory (typically bind-mounted from `./src` by docker-compose.)  For each directory found in `src_extensions`, all pip requirements files matching one of `pip-requirements.txt`, `requirements.txt`, or `dev-requirements.txt` will be installed.  Further each extension that contains a `setup.py` file is itself installed (although not with pip.)

## Miscellaneous

There is no virtual environment, so all package installations effect the system python.  So packages installed at _image build_ time are part of the Docker image and can only be accessed through the image (e.g., via a running container.)

Packages installed at runtime using *ckan-dev* live only inside the running container.

Using pip multiple times to install packages is not ideal.

# Package Management

Let's consider introducing *pipenv*.   Ideally, the package dependencies for the *catalog-app* would be described in a `Pipfile`.  Pinned dependencies are created by "locking" the `Pipfile`, creating a `Pipfile.lock` file.  Pinned dependences can then be installed.   Because the dependencies are pinned, they can be consistently installed.  *pipenv* can also be used to export the pinned dependencies to a *pip*-style requirements file that can be used to deploy *catalog-app* using the ansible infrastructure.

All dependencies would be described in a single location, the `Pipfile`.  All pinned dependencies would be stored in a single location, `Pipfile.lock`.

In the OKFN Docker image world, though, dependency information is scattered across multiple Github repos, multiple Dockerfiles, and (possibly) local files.


# ISSUES

1.  Introducing package management, although desirable, would appear to require extensive changes to the OKFN Docker images.
2.  Because of the use of source mode installs, any simple use of `pip freeze`, for example, to freeze requirements will include source mode references.  We probably don't want this for production.

**Comment by adborden** [comment]
Looks good! It did take `real    17m0.524s` one one test. I'm just going to add a note to the readme.
