### ISSUE TITLE
Local development environment

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#285]
## User Story

As a developer, I want a local development environment that allows me to contribute to catalog application in a more delightful, reliable way, so that the team can iterate more quickly and efficiently

## Acceptance Criteria

WHEN I make a code change to the new catalog app on a feature branch
- [x] THEN the change can be pulled by other developers
- [x] AND there are automated integration tests
- [x] AND the automated integration tests are run as part of CI
- [x] AND branch protection is enforced on master

WHEN I run a single command as per documentation
- [x] AND I open my browser to the local URL as per documentation
- [x] THEN my web browser loads the new catalog application

## Tasks
- [x] Docker CKAN setup
- [x] Automate dev tasks
- [x] Integration Tests
- [x] Configure CI
- [x] Configure Github (Branch protection)

**Comment by starsinmypockets** [comment]
Can someone (@adborden ?) update the settings for https://github.com/GSA/catalog.data.gov to protect the master branch?
