### ISSUE TITLE
Production environment for new catalog app

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#298]
## User Story

As a data.gov developer, I want production-like environment for the new catalog app, so that any issues with the switch over to production are identified as early as possible, before the switch over.

## Acceptance Criteria
WHEN I deploy the data.gov platform to production
- [ ] THEN I can access the new catalog app at its production URL

## Details / tasks
_[adborden] this **appears** large, but the effort isn't significant. Most of the work is fielding BSP tickets and updating configuration in Ansible. As written, it will likely sit in In Progress/Blocked for a sprint or two. _

- [x] Bionic "v2" hosts exist in production
- [x] New RDS database for catalog in BSP (RITM0778862)
- [x] New solr resources (https://github.com/GSA/datagov-deploy/issues/2284)
- [x] Site TLS certificate includes catalog-next.data.gov and admin-catalog-next.data.gov (https://github.com/GSA/datagov-deploy/issues/2147)
- [x] Redis firewall policy (RITM0780651)
- [x] New Load Balancer and/or Netscaler configuration in BSP with new TLS certificate (RITM0781815)
- [x] DNS for catalog-next and admin-catalog-next to point to netscaler (RITM0778863)
- [x] Redis in BSP, similar to https://github.com/GSA/datagov-deploy/issues/1537
- [x] Run db init commands

**Comment by adborden** [comment]
Once we have all the harvesters running, we should see what our database storage usage looks like in order to make a better estimate for the production database size.

**Comment by adborden** [comment]
Opened RITM0778862 for new production RDS.

Opened RITM0778863 to add CNAMEs for catalog-next and admin-catalog-next.

@FuhuXia opened tickets for new solr instances and for the updated TLS certificate. Waiting on the new certificate before opening tickets for the netscaler entries.

**Comment by adborden** [comment]
Moving to blocked until we have the DB and/or the TLS certificate.

**Comment by adborden** [comment]
RDS ticket has been completed. The database was partially initialized following [these steps from staging](https://github.com/GSA/datagov-ckan-multi/issues/296#issuecomment-670771206). However the `ckan db init` command hangs... I don't think solr or redis are setup yet and CKAN is probably waiting for a connection.

**Comment by adborden** [comment]
DNS ticket is completed and verified.

**Comment by adborden** [comment]
Solr is provisioned now. I tried CKAN again, and it looks like it's still hanging. Looks like it _is_ redis: `nc -z -w 15 redis1p.prod-ocsit.bsp.gsa.gov 6379` times out and exits 1.

Opened RITM0780651 to update the Trendmicro firewall policy. I don't remember this coming up in staging...

**Comment by adborden** [comment]
Firewall is updated and CKAN can talk to Redis. I was able to complete the db initialization as well.

Just waiting on an updated TLS certificate so that we can configure Netscaler.

**Comment by adborden** [comment]
The existing certificate works for catalog-next.data.gov, so I'm going to go ahead and create that entry in Netscaler.

**Comment by adborden** [comment]
https://catalog-next.data.gov/dataset is alive!

Still waiting on the new entry for admin-catalog-next.data.gov.

**Comment by adborden** [comment]
BSP checked in on admin-catalog-next.data.gov but it looks like something is not right. Getting an SSL error:
```
$ openssl s_client -connect admin-catalog-next.data.gov:443 < /dev/null
CONNECTED(00000005)
4759725676:error:14004410:SSL routines:CONNECT_CR_SRVR_HELLO:sslv3 alert
handshake
failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.260.1/libressl-2.6/ssl/ssl_pkt.c:1205:SSL
alert number 40
4759725676:error:140040E5:SSL routines:CONNECT_CR_SRVR_HELLO:ssl handshake
failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.260.1/libressl-2.6/ssl/ssl_pkt.c:585:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
Protocol : TLSv1.2
Cipher : 0000
Session-ID:
Session-ID-ctx:
Master-Key:
Start Time: 1605294894
Timeout : 7200 (sec)
Verify return code: 0 (ok)
---
```

**Comment by adborden** [comment]
Confirmed on Friday that the new TLS certificate had been installed, and pushed BSP to complete the Netscaler work. https://admin-catalog-next.data.gov/dataset is now available (although [authentication is still in progress](https://github.com/GSA/datagov-ckan-multi/issues/350) and this work is done.
