### ISSUE TITLE
Discovery 2d: Determine how to rebuild dataset entry form

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#311]
### User story
As an agency user, I can easily add metadata and data that complies with the DCAT standard without having to be an expert in the schema or consult a lot of outside materials, so that my data can be easily discoverable and compliant

### Details/Tasks
- [ ] fields and help and error text can be found here: https://docs.google.com/spreadsheets/d/1mcSkGlQph2CUnlS-I2FAayH6GreF0vLcJiK_Y4iZOM8/edit#gid=0
- [ ] determine implementation details - may build in CKAN, may build in a decoupled front end
- [ ] create implementation ticket with estimate and implementation details

####  "Acceptance Criteria"  Items to validate: 
- [ ] Does existing API interface work the 2.5 API
  - Autocomplete data available from 2.5 API?
- [ ] USWDS basic form with a subset of the fields with inline errors
- [ ] Proof-of-concept implementation required-if-applicable fields
- [ ] Hiding/showing of fields based on previous answers

#### Task-list
 - [ ] Get the existing app that we know works with CKAN 2.8 working with inventory app (for of CKAN 2.5) [Julie and Paul to pair]
 - [ ] Update the form so that it works as per the UX spec as much as possible, in particular, to validate that we do the requirements listed in the AC
 - [ ] Julie to look into the DKAN decoupled app to understand if it's a stand-alone app or can be embedded into CKAN, and more generally the work involved so that it works with CKAN's admin API.  

### Background
Julie produced an estimate to create a metadata / data entry form in CKAN which is 5 to 7 days. As we know we want to extend this form in the future (and CKAN's front-end is inflexible), we're looking into the feasibility of doing it via a decoupled embedded app (embedded to avoid needing an ATO). Datopian has an unpolished react app that works with the CKAN admin API and CA have a decoupled app for metadata entry (decoupled from DKAN). 

### Security Considerations

None for now as just a spike but we'll need to address this.

**Comment by thejuliekramer** [comment]
@adborden After looking into the details of this and talking with @stephen-tsai, @gujacq and @estebanruseler we came up with the following order of items for work with estimates for implementation, #2, #3, #4 are optional. I recommend using a new CKAN theme extension for this implementation, and we can borrow some styles from Dept. of Ed which are based on the USWDS. I initially thought we might be able to make the changes directly in the inventory branch of GSA CKAN but I think since we are bringing in css and some custom javascript now it will be cleaner in an extension

1. New ckanext-inventorytheme extension with new fields (2 days)
2. Add USWDS styles to extension (1/2 day)
3. Dynamic hiding and showing of fields in extension (1/2 day)
4. Setup CI and local docker configuration for local development for extension (1 day)

**Comment by adborden** [comment]
Probably worth a chat to clarify, there's not enough detail here for me to understand what the implementation plan is. Julie and I spoke for a bit today but we didn't have enough time to get into the details.

- Thinking about @gujacq 's designs, are we implementing all the recommended changes, or only a subset? And what timeline are we talking about? e.g. are we saying we will be implementing copy changes, 2-column layout help text, USWDS, error treatment, and conditional form fields (and more?) all in 4 days?
- Can you provide more detail about what will live in the extension? My gut is that we want to do this as a separate app (decoupled frontend, maybe implemented as a CKAN extension), but maybe that's not the right thing to do at this point given non-technical business considerations. I'm looking for more information in order to make this call, or if you've already made that call.
- Have we confirmed that we can build everything we want with CKAN 2.5? We'll be able to reuse Dept of Ed's work without moving to CKAN 2.8?
- How future-proof is this implementation? I my experience, maintaining an alternative design framework (like USWDS) within an existing framework (CKAN) is very difficult. Even if we get it working, what effort is involved in keeping it up to date as USWDS and CKAN are updated?
- Our [Definition of Done](https://github.com/GSA/datagov-ckan-multi/blob/master/CONTRIBUTING.md#definition-of-done) includes CI, so I'm not sure what 4) is referring to, would you clarify?

If you have links to Dept of Ed stuff, or a prototype repo with a partial implementation, that would be very helpful.

**Comment by adborden** [comment]
... @thejuliekramer it might also be helpful if you went ahead and drafted those stories so I can see the specifics.

**Comment by thejuliekramer** [comment]
@adborden I answered some of your questions here - I am waiting for more information from a couple stakeholders and will update when I have that information.

We will implementing a subset of the recommended changes - the main change being left out is the aligned two column layout text on the right side from the original design - but we can implement in the side column on the left, just not aligned or as tooltips or text underneath - I will provide updated screenshots of the mockups with the help of @stephen-tsai 

<img width="448" alt="Screen Shot 2020-06-03 at 9 49 01 AM" src="https://user-images.githubusercontent.com/7378770/83653854-e9cb4b00-a581-11ea-8864-58e0cc0b7c56.png">


I believe this is doable to do the copy changes, modified help text, USWDS, error treatment, and conditional form fields in 7 days - I increased from the original 4 to account for theming difficulties that may happen due to the CKAN 2.5 (bootstrap 2) vs CKAN 2.8 (bootstrap 3) issue.

What will live in the CKAN extension are the templates that will replace the existing CKAN form and the Dept of Ed stylesheets. 

These are specifically, 
[templates/package/snippets/package_form.html](https://github.com/ckan/ckan/blob/master/ckan/templates/package/snippets/package_form.html)
[templates/package/new_package_form.html
](https://github.com/ckan/ckan/blob/master/ckan/templates/package/new_package_form.html)[templates/package/snippets/package_basic_fields.html](https://github.com/ckan/ckan/blob/master/ckan/templates/package/snippets/package_basic_fields.html)

Questions to answer:

1. Have we confirmed that we can build everything we want with CKAN 2.5? We'll be able to reuse Dept of Ed's work without moving to CKAN 2.8?

I have a question out to @tanvirchahal about this - I think the main concern is how heavily the dept of ed theme relies on bootstrap 2 vs 3 but I don't expect this to create more than +1 or +2 day of work even if we adjust to Bootstrap 2 based on the work I did on datagov theme

2. How future-proof is this implementation? I my experience, maintaining an alternative design framework (like USWDS) within an existing framework (CKAN) is very difficult. Even if we get it working, what effort is involved in keeping it up to date as USWDS and CKAN are updated?

I will have to talk with @tanvirchahal about this but even when we move to CKAN 2.8 for inventory Dept of Ed is already using 2.8 so I don't think it would be a huge lift to transition 

3. If you have links to Dept of Ed stuff, or a prototype repo with a partial implementation, that would be very helpful.
@estebanruseler can you help me with links of screenshots for Dept. of Ed please?

**Comment by estebanruseler** [comment]
Updated with react task-list

**Comment by estebanruseler** [comment]
## Outcome of react decoupled/embedded app spike

### Summary of features

| Criteria | CKAN Form | Embedded React app |
| -------- | -------- | -------- |
| Add dataset (Metadata + resource)     |  :heavy_check_mark:    |   :heavy_check_mark:   |
| Ability to customize design and UI     | Subject to bootstrap/CKAN limitations     | More flexibility     |
| ATO needed?     | n/a    | None as embedded in CKAN     |
| Speed     | Moves at "CKAN speed"     | Once loaded, then it's quicker to navigate     |
| Is the form extensible      | Not without coding gymnastics     | More flexibility     |
| Portable into another app     | Not viable     | Could be taken out of CKAN and into eg a workflow app      |

### React Decoupled app (CKAN)

#### What we accomplished with the spike

- [ ] Does existing API interface work the 2.5 API? --> We have the react.js coding working with Inventory app
  - [x] Embedding into Inventory
  - [ ] Autocomplete data available from 2.5 API --> we weren't able to validate this is possible but it should be fine
  - [ ] Metadata / datasets into CKAN --> Not proven but we know from previous work that's possible with our implementation
- [x] Implementation of form fields in React / Bootstrap
- [x] Basic data entry validation
- [ ] Multi-stage dataset wizard --> working with a bug
- [x] Connection between React app and CKAN API
- [x] USWDS basic form with a subset of the fields
- [x] Inline errors
- [x] Proof-of-concept implementation required-if-applicable fields
- [x] Hiding/showing of fields based on previous answers


#### Still to work on

* Overall styling of the form [S]
* File upload working smoothly [M]
* User can't go to next page without completing mandatory fields [S]
* Improved UX of adding dataset (shows datasets that have been added) [S]
* Need to ensure that we can update as well as create [S or M?]

**Comment by estebanruseler** [comment]
@adborden cc team here's the code - https://github.com/datopian/inventory-app/tree/gsa-inventory-reactapp. I also updated the commented last Friday with a comparison CKAN form vs react and some initial thoughts about the tasks remaining to make this  prod ready. 

http://ckan-react-demo.ckan.io - is the react app embedded in CKAN

https://gsa-inventory-app.herokuapp.com - is just the stand-alone react app

**Comment by adborden** [comment]
Thanks! I pulled out this diff which represents the core of the changes (I think) for the react embedded proof of concept: https://github.com/GSA/ckan/compare/inventory...gsa-inventory-reactapp?diff=split

**Comment by adborden** [comment]
ah, but it only has the compiled js for the React App. @estebanruseler can you point me to the React code as well?

**Comment by tanvirchahal** [comment]
@adborden https://github.com/datopian/inventory-app/tree/gsa-inventory-reactapp

**Comment by adborden** [comment]
Quoting Tanvir Chahal (2020-06-15 14:06:55)
> @adborden https://github.com/datopian/inventory-app/tree/gsa-inventory-reactapp

Thanks Tanvir, but I'm looking for the react source code. Not seeing it
in that repo.

--
Aaron D Borden
Human and hacker

**Comment by tanvirchahal** [comment]
@adborden sorry here is the link 
https://github.com/datopian/gsa-inventory-app
