### ISSUE TITLE
Harvester notifications

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#315]
## User Story

As a data publisher, I want to know that my regularly scheduled harvests are successful and if there are any issues, so that I can I can address them.

Upstream work here: https://github.com/ckan/ckanext-harvest/issues/406

## Acceptance Criteria
- [ ] GIVEN a regularly scheduled harvest completes
  THEN the publisher receives an email notifying that the harvest completed and whether it was successful
  AND the subject line includes an indication of whether it is successful. (success = has zero errors)

## Tasks/Implementation details
- [x] publisher needs an email that shows if the job was completed and whether it was successful 
- [x] email links to a more complete report

**Comment by kimwdavidson** [comment]
@hkdctol to document current behavior

**Comment by hkdctol** [comment]
Currently, if an agency wants a harvest report by email every time a harvest completes, we add the agency contact's email to the organization in the admin UI. Then the agency contact receives a report each time a harvest completes, even if there were zero updates or errors

![Screen Shot 2020-06-03 at 3 14 07 PM](https://user-images.githubusercontent.com/3236989/83679387-5740a100-a5ad-11ea-89cb-47abedf02291.png)
![Screen Shot 2020-06-03 at 3 15 19 PM](https://user-images.githubusercontent.com/3236989/83679422-645d9000-a5ad-11ea-8f57-57458d6e189c.png)

**Comment by hkdctol** [comment]
The current harvest report email includes details of errors in a harvest too. But going forward we could have a shorter email and provide only summary, if that makes more sense. Harvest report emails are preferable to creating admin accounts for a lot of agency contacts on catalog.data.gov.

![Screen Shot 2020-06-03 at 3 20 27 PM](https://user-images.githubusercontent.com/3236989/83679674-cfa76200-a5ad-11ea-8bb1-0c8d5465b6f2.png)

**Comment by avdata99** [comment]
We have a [PR](https://github.com/ckan/ckanext-harvest/pull/407) ready to review. This includes basic changes to allow notifications for all jobs based on jinja template

After reading details from @hkdctol we will need to:
 - [ ] Add as recipients the emails at the `extra` value on `email_list`. This custom data is added at the [organization form at the GeoDatGov ext](https://github.com/GSA/ckanext-geodatagov/blob/6a1ac54000310d232dabf005acc5e14e12534be2/ckanext/geodatagov/templates/organization/snippets/organization_form.html#L14-L15) and then used by [the harvest fork](https://github.com/GSA/ckanext-harvest/blob/bb4219462483029fd0b0d7a06403029987f38e89/ckanext/harvest/logic/action/update.py#L646-L648) before sending notifications. This allows us to not create users to receive notifications.
 - [x] Add a link to the job report
   - [ ] Improve the online report with more info

**Comment by avdata99** [comment]
- Moved catalog next to use GSA/harvest fork including our PR to upstream while CKAN/OKF team review it.
 - Merged almost all PRs to use this new feature.

**Almost ready to QA.** 

How to QA:
 - Ensure you have the setting `CKAN__HARVEST__STATUS_MAIL__ALL=True` to get a notification on all harvest jobs (whether it fail or not). This is done at catalog-next repo (ensure [this PR](https://github.com/GSA/datagov-deploy/pull/1758) is merged).
 - Check the _harvest report email list_ field in organization form and add emails if they don't exist.
 - Run a harvest job, when finished you'll see logs errors about trying to send emails to all admin user of the organization + all the custom emails.

**Comment by adborden** [comment]
There was an intermittent build failure on `master` related to Ansible Galaxy, so https://github.com/GSA/datagov-deploy/pull/1758 hadn't been deployed. I saw it was resolved last night and it looks like the change is on sandbox now. Will try to QA again.

**Comment by adborden** [comment]
Here's what I've done so far:

1. Added my email to the `email_list` for the [State of Illinois](https://catalog-next.sandbox.datagov.us/organization/about/state-of-illinois).
1. Trigger a harvest for [illinois json](https://catalog-next.sandbox.datagov.us/harvest/illinois-json).
1. Verified the job completes successfully, with 0 added, updated, deleted
1. Verified in the log:

```
2020-06-24 00:51:33,765 INFO  [ckanext.harvest.logic.action.update] Harvest job run: {}
2020-06-24 00:51:33,810 INFO  [ckanext.harvest.logic.action.update] Marking job as finished https://data.illinois.gov/data.json?version=2 9c0a33e9-67ee-49e7-bad8-379d9690f02c
2020-06-24 00:51:33,855 DEBUG [ckanext.harvest.logic.action.update] Updating search index for harvest source: illinois-json
2020-06-24 00:51:34,010 INFO  [ckanext.harvest.logic.action.update] Notifications: All:True On error:False Errors:0
2020-06-24 00:51:34,155 INFO  [ckanext.geodatagov.plugins] adding chained actions to 2.8.4
2020-06-24 00:51:34,155 INFO  [ckanext.geodatagov.plugins] get_actions 2.8.4 {'package_show_rest': <function package_show_rest at 0x7fdec4fd9b18>, 'datajson_update': <function datajson_update at 0x7fdec4fd9e60>, 'organization_show': <function organization_show at 0x7fdec4fd9b90>, 'location_search': <function location_search at 0x7fdec4fd9a28>, 'datajson_create': <function datajson_create at 0x7fdec4fd9de8>, 'group_catagory_tag_update': <function group_catagory_tag_update at 0x7fdec4fd9d70>, 'package_create': <function package_create at 0x7fdec4fdb1b8>, 'package_update': <function package_update at 0x7fdec4fdb140>, 'doi_create': <function doi_create at 0x7fdec4fd9ed8>, 'doi_update': <function doi_update at 0x7fdec4fd9f50>, 'resource_show': <function resource_show at 0x7fdec4fd9c80>, 'organization_list': <function organization_list at 0x7fdec4fd9c08>, 'group_show': <function group_show at 0x7fdec4fd9aa0>}
2020-06-24 00:51:34,156 INFO  [ckanext.datagovcatalog.harvester.notifications] Adding extra recipients for source 1cbc45a5-a0a4-4e8d-9cd1-7e79f792c6a6
2020-06-24 00:51:34,234 INFO  [ckanext.datagovcatalog.harvester.notifications] Extra recipients for source found: [{'name': u'aaron.borden+illinois@gsa.gov', 'email': u'aaron.borden+illinois@gsa.gov'}]
2020-06-24 00:51:34,234 INFO  [ckanext.harvest.logic.action.update] New recipients added to notification: [{'name': u'aaron.borden+illinois@gsa.gov', 'email': u'aaron.borden+illinois@gsa.gov'}]
```

But I'm not seeing the log message that the email was sent, nor am I seeing the log message in postfix. Instead I'm seeing https://github.com/GSA/datagov-deploy/issues/1795

I think this is good enough for now, since we can't really validate that email is sending in sandbox (the environment is not configured to send mail). So we'll call this done and see if we can send notifications in the staging environment.
