### ISSUE TITLE
Task: Update MAX.gov SAML SP metadata for catalog

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#346]
As part of updating our SAML extensions (https://github.com/GSA/datagov-deploy/issues/1416 https://github.com/GSA/datagov-deploy/issues/1403), we need to generate new Service Provider metadata and provide it to MAX.gov.

[pysaml2 docs](https://github.com/IdentityPython/pysaml2/blob/master/docs/howto/config.rst) describe a `make_metadata.py` script that should be run on the catalog host in order to generate the metadata.

## Tasks/details
- [ ] Run the make_metadata.py script
- [ ] Provide the metadata to @adborden to upload to [MAX.gov](https://community.max.gov/pages/viewpage.action?pageId=1109066197)
- [ ] Rebase https://github.com/GSA/datagov-deploy/pull/1720 and merge
- [ ] Rebase https://github.com/GSA/catalog-app/pull/133 and merge

**Comment by adborden** [comment]
FYI, I ran this script about a year ago and ran into some problems. Because we are not hardcoding information in the config (e.g. reading the site URL from ckan config) the make_metadata.py and the relevant saml config files might need a little massaging in order to run correctly. Once you have some metadata generated, it might be easier to hand-edit rather than getting the script working perfectly.

**Comment by starsinmypockets** [comment]
ckanext-saml2 also has `sp_config.py` which outputs an `sp.xml` file -- attached. It needs to be updated with valid contact info but might be worth forwarding to Rich to see if it works? Maybe we should try both approaches (`pysaml2` -> `make_metadata.py` and `ckanext-saml2` -> `config_sp.py`)? My understanding, however, is that thusfar the max.gov `sp.xml` was being generated by the max branch of `ckanext-saml2`

**Comment by starsinmypockets** [comment]
@adborden Do we need to rerun the make_metadata.py script (which it sounds like you have to fudge anyhow?) or can we just copy/paste the existing sp.xml?

**Comment by starsinmypockets** [comment]
I guess in theory that would "just work" ie we wouldn't need to update anything at Max.gov

**Comment by adborden** [comment]
> ckanext-saml2 also has sp_config.py which outputs an sp.xml file -- attached. It needs to be updated with valid contact info but might be worth forwarding to Rich to see if it works? Maybe we should try both approaches (pysaml2 -> make_metadata.py and ckanext-saml2 -> config_sp.py)? My understanding, however, is that thusfar the max.gov sp.xml was being generated by the max branch of ckanext-saml2

@starsinmypockets I think your comment about the `max` branch and `sp_config.py` is right, although I don't see your attachment. No wonder I couldn't find the docs 🤦 

The [README on the max branch](https://github.com/GSA/ckanext-saml2/tree/max#ckanext-saml2) says to do some configuration and run `/usr/lib/ckan/bin/python /usr/lib/ckan/src/pysaml2/tools/make_metadata.py /usr/lib/ckan/src/ckanext-saml2/ckanext/saml2/config/sp_config.py > sp.xml` so it looks like sp_config.py is part of the configuration for make_metadata.py.

😞  guess we still need to cleanup these branches, too.

**Comment by adborden** [comment]
... and yes, you _could_ tweak the xml by hand, but I would at least start with XML that was generated by an updated pysaml2/ckanext-saml2 configured for staging/production to avoid giving something to MAX.gov (and the back and forth involved) that ends up not working.

**Comment by starsinmypockets** [comment]
@adborden I need contact info for `sp_config.py`to generate the sp.xml for Max.gov :

Org Name,
Org Display Name,
Org URL,

Contact person first and last name
Contact person email

**Comment by adborden** [comment]
Sorry, responded in [slack](https://gsa-tts.slack.com/archives/CDCL978KZ/p1594917255303900?thread_ts=1594916906.303600&cid=CDCL978KZ):
```
OrganizationName: Data.gov
OrganizationDisplayName: Data.gov
OrganizationURL: https://www.data.gov/
ConctactEmail: datagovhelp@gsa.gov
```

**Comment by adborden** [comment]
Duplicate of https://github.com/GSA/datagov-ckan-multi/issues/359
