### ISSUE TITLE
Output clean sp.xml

### ISSUE THREAD

**Issue by starsinmypockets** [GSA/datagov-ckan-multi#359]
As a max.gov I want a an updated SAML2 `sp.xml` file so that Max.gov can config their environment to communicate with catalog / staging.

## Acceptance criteria
- Given that the saml2 work has been deployed to production
- When I log into catalog.data.gov through max.gov
- Then I am successfully authorized 

# Tasks
- [x] Deploy datagov-deploy@saml2-0.4.0-who.ini to staging
- [x] Run catalog playbook with appropriate args to deploy saml2 work
- [x] use instructions from ckanext-saml2 to generate sp.xml
- [x] examine sp.xml
- [x] at staging output clean sp.xml using pysaml2 

Tasks from #346 
- [x] Run the make_metadata.py script
- [x] Provide the metadata to @adborden to upload to [MAX.gov](https://community.max.gov/pages/viewpage.action?pageId=1109066197)
- [x] Rebase https://github.com/GSA/datagov-deploy-common/pull/58 and merge
- [ ] Rebase https://github.com/GSA/datagov-deploy/pull/1720 and merge
- [ ] Rebase https://github.com/GSA/catalog-app/pull/154 and merge
- [ ] Update docs on best practices or gotchas related to generating the metadata

**Comment by adborden** [comment]
@starsinmypockets is this a duplicate of https://github.com/GSA/datagov-ckan-multi/issues/346?

**Comment by starsinmypockets** [comment]
@adborden Here is the sp.xml file that I think we need to give to Max.gov

```xml
<?xml version='1.0' encoding='UTF-8'?>
<ns0:EntityDescriptor xmlns:ns0="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ns1="http://www.w3.org/2000/09/xmldsig#" entityID="urn:mace:umu.se:saml:ckan:sp">
    <ns0:SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
        <ns0:KeyDescriptor use="signing">
            <ns1:KeyInfo>
                <ns1:X509Data>
                    <ns1:X509Certificate>MIIC8jCCAlugAwIBAgIJAJHg2V5J31I8MA0GCSqGSIb3DQEBBQUAMFoxCzAJBgNV
BAYTAlNFMQ0wCwYDVQQHEwRVbWVhMRgwFgYDVQQKEw9VbWVhIFVuaXZlcnNpdHkx
EDAOBgNVBAsTB0lUIFVuaXQxEDAOBgNVBAMTB1Rlc3QgU1AwHhcNMDkxMDI2MTMz
MTE1WhcNMTAxMDI2MTMzMTE1WjBaMQswCQYDVQQGEwJTRTENMAsGA1UEBxMEVW1l
YTEYMBYGA1UEChMPVW1lYSBVbml2ZXJzaXR5MRAwDgYDVQQLEwdJVCBVbml0MRAw
DgYDVQQDEwdUZXN0IFNQMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDkJWP7
bwOxtH+E15VTaulNzVQ/0cSbM5G7abqeqSNSs0l0veHr6/ROgW96ZeQ57fzVy2MC
FiQRw2fzBs0n7leEmDJyVVtBTavYlhAVXDNa3stgvh43qCfLx+clUlOvtnsoMiiR
mo7qf0BoPKTj7c0uLKpDpEbAHQT4OF1HRYVxMwIDAQABo4G/MIG8MB0GA1UdDgQW
BBQ7RgbMJFDGRBu9o3tDQDuSoBy7JjCBjAYDVR0jBIGEMIGBgBQ7RgbMJFDGRBu9
o3tDQDuSoBy7JqFepFwwWjELMAkGA1UEBhMCU0UxDTALBgNVBAcTBFVtZWExGDAW
BgNVBAoTD1VtZWEgVW5pdmVyc2l0eTEQMA4GA1UECxMHSVQgVW5pdDEQMA4GA1UE
AxMHVGVzdCBTUIIJAJHg2V5J31I8MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEF
BQADgYEAMuRwwXRnsiyWzmRikpwinnhTmbooKm5TINPE7A7gSQ710RxioQePPhZO
zkM27NnHTrCe2rBVg0EGz7QTd1JIwLPvgoj4VTi/fSha/tXrYUaqc9AqU1kWI4WN
+vffBGQ09mo+6CffuFTZYeOhzP/2stAPwCTU4kxEoiy0KpZMANI=
</ns1:X509Certificate>
                </ns1:X509Data>
            </ns1:KeyInfo>
        </ns0:KeyDescriptor>
        <ns0:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://login.test.max.gov/slo" />
        <ns0:AttributeConsumingService index="1">
            <ns0:ServiceName xml:lang="en" />
            <ns0:ServiceDescription xml:lang="en">CKAN saml2 authorizor</ns0:ServiceDescription>
            <ns0:RequestedAttribute Name="uid" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true" />
            <ns0:RequestedAttribute Name="name" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true" />
            <ns0:RequestedAttribute Name="mail" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true" />
            <ns0:RequestedAttribute Name="status" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true" />
            <ns0:RequestedAttribute Name="roles" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true" />
            <ns0:RequestedAttribute Name="field_display_name" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true" />
            <ns0:RequestedAttribute Name="realname" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true" />
            <ns0:RequestedAttribute Name="field_unique_id" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true" />
            <ns0:RequestedAttribute Name="field_type_of_user" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true" />
            <ns0:RequestedAttribute Name="field_organization_type" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true" />
            <ns0:RequestedAttribute Name="field_agency" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true" />
            <ns0:RequestedAttribute Name="field_organization" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true" />
        </ns0:AttributeConsumingService>
    </ns0:SPSSODescriptor>
    <ns0:Organization>
        <ns0:OrganizationName xml:lang="en">Data.gov</ns0:OrganizationName>
        <ns0:OrganizationDisplayName xml:lang="se">Data.gov</ns0:OrganizationDisplayName>
        <ns0:OrganizationURL xml:lang="en">https://www.data.gov</ns0:OrganizationURL>
    </ns0:Organization>
    <ns0:ContactPerson contactType="technical">
        <ns0:EmailAddress>datagovhelp@gsa.gov</ns0:EmailAddress>
    </ns0:ContactPerson>
</ns0:EntityDescriptor>
```

**Comment by adborden** [comment]
I've submitted the request to MAX.gov.

**Comment by adborden** [comment]
Pinged MAX.gov about getting the metadata updated.

**Comment by adborden** [comment]
@starsinmypockets and I tested this on Friday but found that authentication with MAX.gov still was not working. We updated metadata and submitted a new version today.

**Comment by adborden** [comment]
Chatted in sync today, we're going to move this to the backlog for now so we can focus on the new metadata app instead.

**Comment by adborden** [comment]
Here's where I think we're at:
- [ ] update who.ini configuration to use the config_max.sp_config
- [ ] fix [bad rebase](https://github.com/GSA/pysaml2/commit/6353a64352be00db97ed16a8079b56da396894e3) in pysaml2 (and if possible, run get the tests running in CI)
- [ ] drop the [GSA/ckanext-saml2 datagov-0.4.0-config branch](https://github.com/GSA/ckanext-saml2/compare/datagov/v0.4.0...datagov-0.4.0-config)
- [ ] re-generate the Service Provider metadata for MAX.gov
- [ ] consolidate PRs, address the outstanding review comments get them re-reviewed and merged

After tracking down the right branches, it looks like whatever metadata we gave to MAX.gov was not using the right config. The config specified in who.ini is pointing to the [template config](https://github.com/GSA/ckanext-saml2/tree/datagov/v0.4.0-config/ckanext/saml2/config) with hard-coded cert/key 👎 

The right branches have yet to be code reviewed, so we'll want to make sure they get reviewed before moving forward.

After specifying config_max.sp_config (and there doesn't seem to be any changes necessary for v0.4.0, hence dropping the datagov-0.4.0-config) we find that pysaml2 wasn't rebased correctly. There's [several variables used that are undeclared](https://github.com/GSA/pysaml2/commit/6353a64352be00db97ed16a8079b56da396894e3).

**Comment by kimwdavidson** [comment]
Resolved by a different approach. Closing
