### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#364]
## User story

As a data.gov team, I want to add analytics capabilities to the catalog-next so we will be able to analyze this data and share with data owners.

## Acceptance criteria

 - GIVEN that a user navigates to the catalog-next public site
   + WHEN they visit a page or use the search function
     - [ ] THEN we capture the analytics data with the same analytics platforms used in the _classic catalog_
     - [ ] THEN we are able to expose these statistics to data.gov team

## Tasks
 - [ ] Confirm with Hyon that we need to use two analytics tracker IDs
 - [x] Install [GSA analytics extension](https://github.com/GSA/ckanext-googleanalyticsbasic) at catalog-next repo
   - [x] Add tests if required
   - [x] Run tests
   - [x] Ensure tests are green in CI

## Details

There is more background information in [DatagovDeploy#1406](https://github.com/GSA/datagov-deploy/issues/1406)

**Comment by thejuliekramer** [comment]
@adborden can you give me and @avdata99 permissions to the ckanext-googleanalyticsbasic repo please

**Comment by avdata99** [comment]
PRs:
 - For analytics ext to add tests and CI config [here](https://github.com/GSA/ckanext-googleanalyticsbasic/pull/2)
 - For new catalog to add the extension [here](https://github.com/GSA/catalog.data.gov/pull/97)
 - For sandbox to add the plugin [here](https://github.com/GSA/datagov-deploy/pull/1989)

**Comment by avdata99** [comment]
How to QA?
Open source code on https://catalog-next.sandbox.datagov.us/dataset and check for analytics code

```
<!-- Digital Analytics Program roll-up, see https://analytics.usa.gov for data -->
<!-- federated_analytics start -->
<script id="_fed_an_ua_tag" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=GSA"></script>
<!-- federated_analytics end -->
<!-- Snippet snippets/googleanalyticsbasic_header.html end -->
```

And
```
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]\|\|function(){
  (i[r].q=i[r].q\|\|[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga_trackers = [];
    
  ga('create', 'UA-1010101-1', 'auto', 'tracker1');
  ga('tracker1.set', 'anonymizeIp', true);
  ga('tracker1.send', 'pageview');
  ga_trackers.push('tracker1');
    
  ga('create', 'UA-1010101-2', 'auto', 'tracker2');
  ga('tracker2.set', 'anonymizeIp', true);
  ga('tracker2.send', 'pageview');
  ga_trackers.push('tracker2');
```

**Comment by adborden** [comment]
@avdata99 is it possible to disable GA by config in production.ini? I think we'll want it disabled for sandbox.

**Comment by woodt** [comment]
Visited the dataset at https://catalog-next.sandbox.datagov.us/dataset/wsrd-radio-receiver-systems-rd-innovation-needs-and-impacts-on-technology-and-policy-works, inspected the HTML source, and confirmed that the two JavaScript snippets indicated above are present.  Also confirmed that there were no JavaScript errors when loading the page (under Chrome.)

**Comment by avdata99** [comment]
> @avdata99 is it possible to disable GA by config in production.ini? I think we'll want it disabled for sandbox.

Should we add a new issue to activate Analytics for stagging and remove it from the sandbox environment?

**Comment by adborden** [comment]
@avdata99 yes, please go ahead and create that issue.
