### ISSUE TITLE
Add code coverage to ckanext-dcat_usmetadata extension

### ISSUE THREAD

**Issue by starsinmypockets** [GSA/datagov-ckan-multi#365]
As a code maintainer I want to monitor code coverage so that I can maintain a high standard of testing for the extension

## Accepance Criteria

- [ ] Code coverage report can be generated locally
- [ ] CI fails on reduced code coverage for commit

## Tasks

- [ ] Get code coverage and report working locally
- [ ] Get code coverage to work with circleci

**Comment by starsinmypockets** [comment]
From Slack:
![Screenshot from 2020-07-28 11-56-23](https://user-images.githubusercontent.com/949175/88690337-8ebd5c80-d0c9-11ea-9459-7a9dca61e506.png)

**Comment by starsinmypockets** [comment]
cc @woodt we can continue discussion here?

I also think adding coverage report with no failure case is fine for now.
