### ISSUE TITLE
Bug: User can submit without required tags

### ISSUE THREAD

**Issue by starsinmypockets** [GSA/datagov-ckan-multi#410]
## Acceptance Criteria

- [ ] WHEN I visit the form page in sandbox
- [ ] AND try to submit the first page without any tags added to the tag field
- [ ] THEN I see and error message explaining that I need to add tags in order to submit
- [ ] AND when I add tags to the tags field (type tag name, then enter)
- [ ] THEN the validation message is gone

## Description

Bug: 
Expected Behavior:
- When I don't fill in the tags, which is a required field, I should see an error message and be unable to submit the form.

Current Behavior:
- I do not see an error message and am not blocked from submitting the field.

## Details: 
Tags "field" is not actually a field and is currently not included in Formik validation even. Requires integration work.

## Tasks

- [ ] id strategy for validating tags field via Formik
- [ ] implement

**Comment by starsinmypockets** [comment]
![Screenshot from 2020-08-28 13-20-57.png](https://images.zenhubusercontent.com/565c88e4638e718c995ef42d/8e240d72-ba39-4100-9174-dd98de61e9f6)

caption: Tags field here should be highlighted as error. Tags field should also be listed at the top of the form as a validation error

**Comment by cmugisha** [comment]
@starsinmypockets This ticket was estimated at half a day. Any updates?
