### ISSUE TITLE
Metadata app -- Update required field choices with correct values

### ISSUE THREAD

**Issue by starsinmypockets** [GSA/datagov-ckan-multi#423]
# User Story
As a data publisher I want to be able to select valid choices for required data so that I can publish my data,

# Acceptance Criteria
- [ ] WHEN I visit the new-metadata page
- [ ] AND select the _Publisher_ field
- [ ] THEN I see the expected values
- [ ] WHEN I visit the new-metadata page
- [ ] AND select the _Subagency_ field
- [ ] THEN I see the expected values in the dropdown

# Tasks
Determine dropdown choices for:

- [ ] Publisher
- [ ] Subagency

**Comment by starsinmypockets** [comment]
cc @stephen-tsai @gujacq -- this is what I want to discuss on Monday

**Comment by kimwdavidson** [comment]
Duplicate
