### ISSUE TITLE
Task -- Remove "Meets Agency Data Quality" fied from form page 1

### ISSUE THREAD

**Issue by starsinmypockets** [GSA/datagov-ckan-multi#428]
## Acceptance Criteria

- [ ] WHEN I visit https://inventory.sandbox.datagov.us/dataset/new-metadata?group=123
- [ ] THEN I do NOT see the "Meet Agency Data Quality" field on the first form page
- [ ] AND WHEN I visit the second form page (Additional Metadata)
- [ ] THEN I see the "Meet Agency Data Quality" field 

## Description
"Meets Agency Data Quality" field should be on the additional metadata page, not on the required metadata page. It's currently on both. 

# TASK
- [ ] Remove field from page 1

**Comment by starsinmypockets** [comment]
I think that this is required by the USMetadata extension, I will double-check

**Comment by starsinmypockets** [comment]
Apologies -- this is NOT required by USMetadata app it's ok to remove it
