### ISSUE TITLE
Implement tags field for Additional Metadata "themes" field

### ISSUE THREAD

**Issue by starsinmypockets** [GSA/datagov-ckan-multi#430]
# Tasks

- [ ] Copy tags field to Additional Metadata "themes" field

# Notes

This field should also load CKAN tags with autocomplete

**Comment by kimwdavidson** [comment]
currently estimated at about an 8, can we break this into smaller tickets?

**Comment by anuveyatsu** [comment]
@adborden can we clarify if we just need to copy "tags" to themes field? It's unclear to me because I'm not sure how it's going to work:

1. Read available tags from CKAN.
2. Render it for "themes" field (eg, when showing options for autocomplete).
3. User selects a theme and submits the form.
4. Selected theme is written to CKAN as "theme" (or "category" as I can see in USMetadata extension).

Now, what happens if theme doesn't exist in list of tags? Should we create a new tag behind the scenes?

**Comment by anuveyatsu** [comment]
@adborden other option for me would be creating a separate object from tags in the CKAN which is called themes or categories. Below is what would be AC and tasks for it:

## Acceptance criteria

* [ ] When on additional metadata page, I can
  * [ ] type in related theme for my dataset
  * [ ] select from already existing themes, eg, by searching (autocomplete)
  * [ ] create a new theme if it doesn't exist

## Tasks

* [ ] Create a new table in the DB, eg, `theme` where we store theme names
  * [ ] Clarify if we need to have human readable versions of the themes, e.g., `apples-and-bananas` => `Apples and bananas`
  * [ ] Store theme name and title
* [ ] Implement APIs
  * [ ] a read API so we can retrieve list of available themes
  * [ ] a write API so we can write a new theme into the db
* [ ] Refactor Metadata app

**Comment by kimwdavidson** [comment]
@adborden to provide feedback on plan
