### ISSUE TITLE
Submit an API or indirect download resource

### ISSUE THREAD

**Issue by anuveyatsu** [GSA/datagov-ckan-multi#529]
Based on discovery work done in https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/524, we're creating this issue for implementation work.

[Should follow the approved design](https://github.com/GSA/datagov-ckan-multi/issues/524#issuecomment-746842489)

## Acceptance criteria

- [x] GIVEN I add a resource with "Link to a file"
  WHEN I browse to my organization page
  AND I click Export Redacted Data.json
  THEN I see my resource with the `downloadUrl` field populated with my URL.
- [x] GIVEN I add a resource with "Upload a file"
  WHEN I browse to my organization page
  AND I click Export Redacted Data.json
  THEN I see my resource with the `downloadUrl` field populated with an inventory.data.gov URL.
- [x] GIVEN I add a resource with "Link to an API"
  WHEN I browse to my organization page
  AND I click Export Redacted Data.json
  THEN I see my resource with the `accessUrl` field populated with my URL
  AND the format field is "API".
- [x] GIVEN I add a resource with "Access URL"
  WHEN I browse to my organization page
  AND I click Export Redacted Data.json
  THEN I see my resource with the `accessUrl` field populated with my URL.

## Tasks

* [ ] Add 4 new radio buttons on "Resource Upload" page with following labels:
  * [x] "Link to a file" - this replaces "Link to data" button
  * [x] "Link to an API"
    * [ ] When this option is selected, a resource metadata should have additional metadata:
      * [ ] `"resource_type": "accessurl"`
      * [ ] `"format": "API"` - we already have "format" field in the form so just need to add another option there and auto select
  * [x] "Access URL"
    * [ ] When this option is selected, a resource metadata should have additional metadata:
      * [ ] `"resource_type": "accessurl"`
  * [x] "Upload a file" - this replaces "Upload data" button 

* [ ] Display input element similar to current "Link to data" option, when any of these buttons is clicked
* ~~Implement mapping of values from those options so that it follows DCAT spec~~ will be done by tasks above
* ~~Refactor "Upload data" option to follow DCAT spec~~ already done
* [ ] Add integration tests for all new options

**Comment by kimwdavidson** [comment]
awaiting @adborden's approval, then @anuveyatsu's estimate

**Comment by adborden** [comment]
Updated the AC, looks good.

**Comment by anuveyatsu** [comment]
This is how redacted `data.json` file is exported at the moment (note `distribution` attribute with 4 different resources):

```json=
{
  "@type": "dcat:Dataset",
  "title": "Resource types 2",
  "description": "Resource types 2",
  "modified": "2021-01-13T05:31:39.428Z",
  "accessLevel": "public",
  "identifier": "unique id 1020314",
  "license": "https://opensource.org/licenses/MIT-0",
  "rights": "true",
  "publisher": {
    "@type": "org:Organization",
    "name": "General Services Administration"
  },
  "contactPoint": {
    "@type": "vcard:Contact",
    "fn": "Anu",
    "hasEmail": "mailto:anu@test.com"
  },
  "distribution": [
    {
      "@type": "dcat:Distribution",
      "mediaType": "text/csv",
      "title": "Remote URL",
      "downloadURL": "https://example.com/data.csv"
    },
    {
      "@type": "dcat:Distribution",
      "mediaType": "image/png",
      "title": "Random screenshot of metadata app",
      "downloadURL": "https://inventory.sandbox.datagov.us/dataset/375e85a0-fb75-4cbe-a79a-c41ae5c880c5/resource/f7c2ed1b-d998-4f3b-818b-9081bd0712dd/download/screen-shot-2020-12-08-at-13.31.41.png"
    },
    {
      "@type": "dcat:Distribution",
      "accessURL": "https://www.access-url.com",
      "title": "access-url"
    },
    {
      "@type": "dcat:Distribution",
      "accessURL": "https://www.access-url.com/api",
      "title": "access-url-api"
    }
  ],
  "keyword": [
    "test"
  ],
  "bureauCode": [
    "015:11"
  ],
  "programCode": [
    "015:001"
  ],
  "language": [
    "en-US"
  ]
}
```

cc @kmanaseryan

**Comment by adborden** [comment]
I think API should have `"format": "API"`

**Comment by anuveyatsu** [comment]
Updated the tasks section of this issue.

cc @kmanaseryan
