### ISSUE TITLE
[bug] edited datasets are not correctly loaded in the new metadata form

### ISSUE THREAD

**Issue by osahon-okungbowa** [GSA/datagov-ckan-multi#547]
## Description
when a dataset in the inventory sandbox is edited, **not all** field values are loaded/prefilled into the new metadata form 

## How to reproduce

1. Visit `/datasets` and click on any dataset title to edit
2. click on the `Edit` button
3. change the `License` field dropdown value to `N/A`
4. click `Save and Continue` and publish the dataset
5. click on the `Edit` button again and click on `Save and Continue`.
6. observe the error message that indicates the License field value is not set

## Expected behavior

1. **All** field values of the saved dataset are correctly loaded into the metadata form

## Actual behavior

1. When editing saved datasets, some field values are not loaded into the metadata form

## Tasks
- [x] Fix "other" option with custom value in "Data Dictionary Type" and "Data Publishing Frequency" dropdowns should be pre-populated as well
- [x] N/A License field should be fixed
- [x] Create new tests for those edge cases

**Comment by hkdctol** [comment]
this has been fixed.
