### ISSUE TITLE
Harvest improvement discovery

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#56]
User research and analysis to inform harvest improvement and provide next steps.

## Tasks

* [x] User interviews (x2) to get background and user epics
* [x] List of user epics
* [x] Existing code analysis of CKAN Harvesteer
* [x] Existing code analysis of harvesters esp of data.json harvester
* [x] Analysis for next steps

**Comment by jqnatividad** [comment]
Will distribute a gdoc on June 10 to prep for the Harvest deep dive.

@kimwdavidson, can you add me as an assignee?

**Comment by jqnatividad** [comment]
Here are the gdoc notes 

https://docs.google.com/document/d/1Fw1lzKuy90kh84KlK3p3R-5fnQM7gH13UjZqIw3u-to/edit

**Comment by rufuspollock** [comment]
We have collected all current epics from the discussions into a spreadsheet and have worked through quite a bit of the code analysis and are prepping an initial plan of work.

**Comment by rufuspollock** [comment]
FIXED.
