### ISSUE TITLE
Research and Set up logging

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#59]
User story:  As a cluster admin I want to be able to see and manage in one central location (rancher) logs from all containers in the cluster

## Acceptance criteria

* [x] Logging system installed and operational on GSA cluster

## Tasks

 * [x] Research options (and needs) and recommend => ELK looks good
 *  [x] Install ELK stack on the cluster  (assuming this is the one to go for)
   * [x] Set up Elasticsearch
   * [x] Set up Logstash
   * [x] Set up Kibana
 * [x] Integrate with Rancher
 * [x] Test to make sure logs are being received
 * [x] Update configuration for easy filtering

**Comment by jqnatividad** [comment]
@JJediny mentioned during Jun 10 2019 standup that he prefers that we stay with typical k8s logging mechanisms rather than reinventing the wheel.

Also, all ideas welcome in terms of setting this up in a way consistent with GSA's "infrastructure as code" goals.

**Comment by aabond** [comment]
@jqnatividad Would you happen to have any links or documentation regarding GSA's "infrastructure as code" goals?

**Comment by kimwdavidson** [comment]
Need to determine what we want to be logging

**Comment by aluminiumgeek** [comment]
I added Jenkins job that installs and sets up ELK stack on the cluster.
It's now up and running on the GSA cluster.
Kibana external URL: http://a81ec16c3a6f511e987df021ee0764bf-2082103619.us-west-2.elb.amazonaws.com/app/kibana

Logstash is currently set up for TCP input. You will probably want to enable more input plugins. Here's the list of available input plugins: https://www.elastic.co/guide/en/logstash/current/input-plugins.html

**Comment by adborden** [comment]
@aluminiumgeek can you link me to the relevant PR?

**Comment by adborden** [comment]
@aabond we don't have any goals written down, though I would be happy to work with you in order to do that.

**Comment by adborden** [comment]
@kimwdavidson @aluminiumgeek I haven't been able to QA this work. Is there a PR or instructions on how to QA?

**Comment by kimwdavidson** [comment]
@rufuspollock to add QA instructions

**Comment by rufuspollock** [comment]
@kimwdavidson this one i don't think was for me. It should be for @aluminiumgeek (and @akariv). @aluminiumgeek  will update.

**Comment by aluminiumgeek** [comment]
@adborden 

CCO itself doesn't contain code for ELK setup.

I've created a Jenkins job that installed and configured ELK on the cluster from scratch. [Here is it](https://cc-p-jenkins.datagov.us/job/Set%20up%20ELK/).

To see available pods in stack, run
`kubectl -n elasticsearch get po`

Logstash is currently set up for TCP input. So you could test it with `netcat` or other similar utility:
```
echo "sample log message" | nc a800cdb95a6f511e987df021ee0764bf-1102686912.us-west-2.elb.amazonaws.com 5044
```

And then see the received message in Kibana: http://a81ec16c3a6f511e987df021ee0764bf-2082103619.us-west-2.elb.amazonaws.com/app/kibana

**Comment by akariv** [comment]
We should probably add an issue with the following task -

-  Connect instances to the logging system
- configure logatash to parse ckan logs correctly
- set up domain and authentication on kibana instance

Acceptance criteria:
Being able to easily read the logs of a specific instance from a specific
time range

**Comment by adborden** [comment]
@aluminiumgeek so if we lose the Jenkins instance, how can we re-create the job? Is it documented? It looks like it's mostly kubectl configuration, why can't that be bundled into a helm chart or similar?

**Comment by rufuspollock** [comment]
@adborden so we track this work I've created a follow up dedicated issue in #127. I wonder if we could close this and follow up there? wdyt?
