### ISSUE TITLE
[Epic] Harvesting Improvements Phase I

### ISSUE THREAD

**Issue by rufuspollock** [GSA/datagov-ckan-multi#70]
In this initial phase we propose exploring a new "next gen" approach to harvesting. This will include standing up test instances of CKAN v2.8.

Pursuing two tracks

* Stand up internal test instances with latest CKAN Classic and install extensions
* CKAN Next Gen approach - create a clean separation of ETL that allows for easier development and testing of harvesters as well as better performance and monitoring

## Acceptance criteria

* [x] First pass on next gen approach for ETL system
* [x] CKAN v2.8 running on dev machines
* [ ] Harvest sources from catalog.data.gov are imported, scheduled, and running a daily harvest

## Tasks

High level

* [x] Get a list sample sources to work on 
  * [x] Go through JSON output and find the data.json urls and put them in the [spreadsheet][ss]
  * [x] Use these (starting with one e.g. Dep of Ed) as your test data
* [x] Trial the migration of data.json harvest
* [x] Get setup with CKAN and harvesting (in parallel) - https://github.com/GSA/datagov-ckan-multi/issues/71

### Next Gen approach

Trial a migration of data.json harvest to a separate ETL framework that can integrate with CKAN Classic harvest

Part I

* [x] Write a simple test using TDD.
* [x] Get sample data.json files (maybe cut one down for testing - we don't need a whole file)
* [x] Retrieve a data.json file and validate it.
  * [x] Retrieve it (cache it)
  * [x] Validate it (output the validation report as a csv/json file somewhere)
* [x] Parse the data.json, convert each dataset into a data package and store this in a scratch directory

Part II: do the same but with updating ...

* [x] start with test code ...
  * [x] data.json source and source_id ... 
* [x] Get list of existing datasets on data.gov filtered by harvest_source_id
* [x] Compare both resources to find differences
* [x] Implement the change algorithm ... 
  * [x] Analyze existing code and write out the algorithm (good practice anyway)
  * [x] then implement

**Comment by kimwdavidson** [comment]
@philipashlock to send list of harvest sources to @rufuspollock

**Comment by kimwdavidson** [comment]
from john: to get this current list of our harvest sources w/ the metadata source endpoints, you can use this api call `https://catalog.data.gov/api/3/action/package_search?q=%28type:harvest%29&rows=1000`

**Comment by rufuspollock** [comment]
Updated with more description and subtasks.

**Comment by adborden** [comment]
This is the AC I added:
> Harvest sources from catalog.data.gov are imported, scheduled, and running a daily harvest
