### ISSUE TITLE
Improvements to CCO including GCP support

### ISSUE THREAD

**Issue by rufuspollock** [GSA/datagov-ckan-multi#72]
We want to test the new CCO setup in a dev setup and document to make sure it is easy for others to use and get setup (and this includes checking GCP support as this is default deployment mode).

# Tasks

- [x] Run CKAN Cloud Operator from the v2 branch locally
- [x] Create a new k8s cluster in the sandbox project and document
- [x] Get up and running on Google Cloud (this should be relatively easy)
  - [x] Keep a detailed log of actions
  - [x] Update the main documentation as needed

# Acceptance criteria

- [x] Document which is a log of all steps taken to get a cluster up and running and controllable with CKAN Cloud Operator
- [x] Update the primary documentation with any missing steps, or required comments

**Comment by rufuspollock** [comment]
Set up on the cluster. Ran CCO. Everything running but SOLR.
