### ISSUE TITLE
Clean up codebase of base CKAN Cloud Docker image

### ISSUE THREAD

**Issue by rufuspollock** [GSA/datagov-ckan-multi#73]
Recent deployments using the CKAN Cloud Docker codebase brought to light a range of potential improvements related to e.g. missing documentation, security improvements and ineffective deployment work flows.

Before diving into what needs to be done, let's review what [CKAN Cloud Docker][ccd] is, and why we use it.

[ccd]: https://github.com/ViderumGlobal/ckan-cloud-docker

CKAN Cloud Docker is a codebase we use to provide the core elements of our approach to CKAN Cloud deployments based on CKAN Cloud Operator.

# Tasks

- [x] Remove secrets from the codebase
  - We could have a *template* for a file that can be read by a deployment to provide all secrets, and this file could indicate which env vars are required and which are optional
  - We should document how secrets are provided when calling `docker-compose up`, or similar
  - Note that this is not just about the ckan-secrets.sh file, but also things in compose files like a hard-coded 123456 password for databases.
- [x] Remove instance-specific info from the codebase
  - This codebase should have the docker compose files needed in generic cases. The instance-specific Docker compose files (for example [here](https://github.com/ViderumGlobal/ckan-cloud-docker/blob/master/.docker-compose.vital-strategies-theme.yaml) and [here](https://github.com/ViderumGlobal/ckan-cloud-docker/blob/master/.docker-compose.datagov-theme.yaml)) should be completely removed, and then we can document a pattern from creating private repos for those instance specific configuration files, and pulling those in for deployments.
- [x] Configuring transactional email
  - Ensure that this is documented. If there is a way to make a deployment fail if no SMTP creds provided, even better. On deployments of machines that Datopian manages, we can use credentials from our own transactional email providers. For machines that client's manage, we need to tell them what they do (eg: get creds from sendgrid, mandrill, mailgun or similar).
  - [Some of this might be relevant](https://docs.ckan.org/en/2.8/maintaining/installing/deployment.html)
- [x] Only expose necessary public ports
  - That should only need to be 80 and 443. Currently, the config uses `port` instead of `expose` which publishes many ports.
- [x] Be explicit about enabling/disabling features that may not be required for a given deployment. For example, s3filestore and sentry are part of the default setup, but in many cases sentry may not be needed, and an instance may use the local filesystem rather than an S3 object store.
- [x] Slow connections and lots of network traffic
  - Possible problem with http://raw.githubusercontent.com/ - [ckan post install functions.py](https://github.com/ViderumGlobal/ckan-cloud-docker/blob/master/ckan/post_install_functions.sh) is trying to retrieve requirements.txt remotely and install packages that way. This was taking so long that we've been waiting ~20 minutes installing just 2 extension dependencies.
- [x] More stuff pre-built
  - Maybe we can have much more of the stack pre-built so that deployments are easier. Need to check.

## Optional/investigative tasks

- [ ] We currently deploy but then have no monitoring. Monitoring is not always our responsibility, but we need a clear story around it, and the ability to enable or disable additional monitoring for CKAN Cloud Docker deployments. 
- [ ] Likewise with backups and volume recovery.

# Acceptance criteria

- [x] Fresh deploy with CKAN Cloud Docker on a VM
- [x] A clear PR or series of PRs that implement these fixes
- [x] Documentation for fresh deployments using CKAN Cloud Docker (i.e.: [update the existing documentation here](https://github.com/ViderumGlobal/ckan-cloud-docker/blob/master/DEPLOYING.md))
