### ISSUE TITLE
Full CCO documentation including Deployment Guide

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/datagov-ckan-multi#74]
We want to create high quality "public release" grade documentation for the CKAN Cloud Operator and its use so that it is completely usable by others. Work may also include tidying the code base, publishing docs online etc.

Note: we want to document CCO as an open source tool -- that way we maximize potential for reuse and contribution. Thus design documents for general use and then document separately any GSA specific items.

## Acceptance criteria

* [ ] Someone at CA and/or at data.gov can deploy 
* [ ] Nice home page for the docs with walkthrough

## Tasks

* [x] Relocate CCO repo to correct location (e.g. under github.com/datopian)
* [x] Research examples of great documentation setups
  * [ ] Check if we are going to use plain README or deploy to a mini-website (e.g. using vuepress etc)
* [ ] Main documentation (see below)
  * [x] DevOps
  * [x] Cluster Manager
  * [x] Developer (e.g. contributing)
  * [ ] Home page for it all

### DevOps
See https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/123

### User guide
See https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/124

* [x] Creating new instances etc
* [x] ...

### Developer Guide
https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/134

### Misc

* [ ] Authors and Credits
* [ ] Get support etc

### GSA specific docs

* [ ] Create any specific GSA repos
* [ ] GSA specific docs (to maximum extent possible we want docs to be of generic open source tool so that we maximize open source aspect but there still may be some GSA specific items)

**Comment by rufuspollock** [comment]
Started and in early stages.

**Comment by aluminiumgeek** [comment]
I moved the repo to Datopian organization. Updated the code to point to the new repository URL.

I'll start working on other things next week.

**Comment by tkprmr** [comment]
Hi Mikhail, can you post the link of the document also so whoever wants to start reviewing then can do so

**Comment by jqnatividad** [comment]
The repo is at https://github.com/aluminiumgeek.

To track this more easily, converted this to an Epic, and broke up the different deliverables to its own ticket.

**Comment by aluminiumgeek** [comment]
@tkprmr 
Full documentation is [here](https://github.com/datopian/ckan-cloud-operator/blob/full-documentation/docs/DOCUMENTATION.md). It currently contains DevOps guide. Other parts are coming.

**Comment by aluminiumgeek** [comment]
Updated [docs](https://github.com/datopian/ckan-cloud-operator/blob/full-documentation/docs/DOCUMENTATION.md) adding User Guide section.

**Comment by jqnatividad** [comment]
Closing this as CCO deployment is being automated and the associated documentation revamped to reflect this (#167).
