### ISSUE TITLE
Unit Testing CCO

### ISSUE THREAD

**Issue by akariv** [GSA/datagov-ckan-multi#75]
We want to test the CCO tool to ensure that functionality does not break when making changes to the code. In order to do so we'd like to create a suite of tests that will be run automatically on each proposed change.
These tests will be done as a way to ensure the correctness of new proposed version of CCO (which is now running on the GSA cluster).

# Tasks

- [x] Map current functionality of CCO
- [x] Write test suite for CCO:
  - Sanity tests for each category (1st priority)
  - Integrative tests combining different aspects of the tool (2nd priority)
  - In-depth tests for each category (3rd priority)
- [x] Design test environment
- [x] Implement test environment
- [x] Implement individual tests
- [x] Create CI task
- [x] Integrate with coverage measurement service

# Acceptance criteria

- [x] A test suite document (spreasheet)
  - A List of tests (Title, Priority, Steps, Expected result, later: link to code / name of test function)
- [x] A CI task that runs the tests on every push/PR
- [x] A coverage metric showing the percent of the code that is covered by the test suite

**Comment by adborden** [comment]
For the code coverage, is there an initial metric you're aiming for? Or is the goal to just make sure that we're measuring it to start?

**Comment by aluminiumgeek** [comment]
[Test suite document (spreadsheet)](https://docs.google.com/spreadsheets/d/1CNBdTL-3s_jlEpB7_vcknqnpkKFWkWfyWVlHFYMVnHc/edit?usp=sharing)

[Pull request](https://github.com/ViderumGlobal/ckan-cloud-operator/pull/63)

Also added new command that runs test suite and collecting coverage metrics: `ckan-cloud-operators test`.

CI runs test suite on every push / pull request.

**Comment by akariv** [comment]
Thanks, looks really good.
I left a small review comment (next time please ask a review via the GitHub
interface please :) )
Is there any indication of current test coverage?

**Comment by adborden** [comment]
@aluminiumgeek thanks! This looks good. I assume all the items in the spreadsheet are covered? If so you can go ahead and merge that PR from my perspective and I will close this out.

**Comment by aluminiumgeek** [comment]
@adborden 
>  I assume all the items in the spreadsheet are covered? 

Correct. I merged the PR.


@akariv
> Is there any indication of current test coverage?

Yes. `ckan-cloud-operator test` command or `coverage run -m unittest discover` command collects and prints coverage stats.
