### ISSUE TITLE
Multi-tenant platform security and ATO roadmap

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-ckan-multi#98]
As a system owner, I need to know what high level milestones need to be met and in which order for ATO so that I have an idea of where the risks are, what objectives any sprint tasks need to meet, and have some measuring stick to approximate when the platform will be production ready.

## Acceptance criteria

- [x] Description of each milestone on the path to ATO.
- [x] Include some criteria that would be met when we meet the milestone such that it's clear if we have or haven't hit the milestone.
- [x] Include any known risks with each milestone.
- [x] All the above documented in a Google Doc.

**Comment by kimwdavidson** [comment]
For reconsideration when we know about FedRAMP vs. tailored

**Comment by adborden** [comment]
I think we can close this is done. The [ATO issue](https://github.com/GSA/datagov-ckan-multi/issues/158) will track the roadmap tasks.
